### ISSUE TITLE
Label all the closed issues in standard way

### ISSUE THREAD

**Issue by sandhawke** [w3c/activitystreams#325]
Please Indicate One: 
 * [ x] Editorial
 * [ ] Question
 * [ ] Feedback
 * [ ] Blocking Issue
 * [ ] Non-Blocking Issue

Please Describe the Issue:

For the CR transition meeting we'll need to make clear how all the issues were resolve, ie to the commenters satisfaction or not.

**Comment by evanp** [comment]
Ugh. That's 300+ issues.

**Comment by rhiaro** [comment]
Nae worry, I did it at the weekend :)

**Comment by akuckartz** [comment]
:+1:

**Comment by evanp** [comment]
Wow! Nice job, @rhiaro !
