### ISSUE TITLE
Use BCP 47 rather than RFC 5646

### ISSUE THREAD

**Issue by r12a** [w3c/activitystreams#333]
Please Indicate One: 
 * [ ] Editorial
 * [ ] Question
 * [ ] Feedback
 * [x] Blocking Issue
 * [ ] Non-Blocking Issue

This issue has support from others in the i18n WG.

Throughout 
https://www.w3.org/TR/activitystreams-core/ and
https://www.w3.org/TR/activitystreams-vocabulary/
RFC 5646 is listed as the reference for language tags. This should be BCP 47, so that it is future-proof.  (BCP 47 includes RFC 5646, but will include it's future replacement too – it was specifically created to provide a stable link.)

**Comment by akuckartz** [comment]
The JSON-LD spec also refers to BCP 47.

**Comment by r12a** [comment]
Thank you.
