### ISSUE TITLE
How to know the language of a natural language value when there is no translation?

### ISSUE THREAD

**Issue by r12a** [w3c/activitystreams#335]
Please Indicate One: 
 * [ ] Editorial
 * [ ] Question
 * [ ] Feedback
 * [x] Blocking Issue
 * [ ] Non-Blocking Issue

[This issue has support from others in the i18n WG.]

For example at https://www.w3.org/TR/activitystreams-core/#naturalLanguageValues

It is often important for rendering to know the language of the natural language text, ie. for automatic selection of appropriate fonts when dealing with Chinese vs Japanese, for line breaking rules, for pronunciation by voice browsers, for automated translation, for hyphenation, etc...

Therefore there needs to be a way to identify the language of every item of natural language text.

The explanations in the spec currently seem to imply that `nameMap`, etc, are only used when there are multiple translated versions available, and that if you use `name` there is no way to indicate the language of the text. (If this is an incorrect interpretation, there should at least be a note to clarify it.)

We would like you to provide a simple way of identifying the language of `name`, `summary` and `content` properties.

If there is no straightforward way to do this, we think the spec should at least indicate the importance of providing language information and encourage people to use the `xxxMap` property by default rather than the alternative, so that language information can be carried, eg. 

```
{...
"contentMap": { "en": "A simple note" }
}
```
and change the examples to reflect that.

**Comment by jasnell** [comment]
When using the non-map version of the natural language fields (`content`, `summary`, and `name`), the assumption is that those fields are explicitly *not* language tagged, which would make it necessary to use an out of band mechanism (such as the http `Content-Language` header) to identify the default language.

The Activity Streams vocabulary is designed around JSON-LD but specifically does not *require* that consumers use JSON-LD algorithms to process AS documents. JSON-LD does include the ability to specify a default language as part of the `@context` mechanism. For implementers who do choose to process AS documents using the JSON-LD algorithms, this `@language` property can be leveraged.

**Comment by evanp** [comment]
I disagree with @jasnell that the best way to handle this is to recommend using the *Map format for all natural-language fields. I've removed this (normative!) change, and we'll discuss it in our teleconference today.
