### ISSUE TITLE
It should be possible to indicate the default base direction for natural language values

### ISSUE THREAD

**Issue by r12a** [w3c/activitystreams#336]
Please Indicate One: 
- [ ] Editorial
- [ ] Question
- [ ] Feedback
- [x] Blocking Issue
- [ ] Non-Blocking Issue

[This issue has support from others in the i18n WG.]

In addition to language information, each annotation may need an optional indicator of overall base direction when dealing with scripts such as Arabic, Hebrew, Thaana, etc.

For example, the following summary will not display correctly unless the application doing the display knows that the base direction needs to be rtl. (As it is, the 'W3C' will appear to the right, as shown here, rather than to the left of the Hebrew summary.) 

```
{
  "@context": "http://www.w3.org/ns/activitystreams",
  "name": "A simple note",
  "type": "Note",
  "summary": "פעילות הבינאום, W3C"
}
```

Some way should be provided to enable identification of the default base direction for an item containing natural language.

**Comment by jasnell** [comment]
While I agree with this in general, it is a general problem with JSON and JSON-LD in *general* and not just Activity Streams. For the `content` and `summary` (and corresponding `contentMap` and `summaryMap` properties, HTML markup can be used to identify the direction, e.g. `"summary": "<p dir="rtl">...</p>"`. For the `name` and `nameMap` fields that do not allow such markup, the Unicode bidi control characters can be used. A short section dealing with the use of bidi text is something that I could easily work up.

**Comment by r12a** [comment]
Reopening this, since i believe it's the topic of our discussion last Thursday.

I have created some notes that may help with the discussions.  See
https://www.w3.org/International/wiki/Activity_Streams_direction_notes

**Comment by r12a** [comment]
Adding comments here so that subscribers are notified (rather than to the PR).  This refers to https://github.com/w3c/activitystreams/pull/352

Suggestions interlined:

> Bidirectional Text
> 
> The default direction of any natural language value may be determined in the following manner:
> 
>  1.  Explicitly prefixing the value with a Unicode Bidirectional Control character [[!BIDI]] that identifies text direction;
>  2.  Locating the first strong directional character that is not contained within a markup element;

I think the default is the second bullet point, since the explicit thing only needs to be done where there would otherwise be an incorrect result.  So i suggest to reverse the order of the first two list items, and perhaps add text to the resulting second item to the effect that this is necessary only where the result would otherwise be incorrect.

I suggest to change the order of items in the table to match.

> 3.  When using either the content or summary properties (or their corresponding contentMap and summaryMap variants), using HTML markup to explicitly identify the text direction.

I'm guessing that you don't mean here that for content or summary properties you _have_ to use markup to identify the direction, since in the previous bullet you talk about skipping the markup.

> Property 	Value 	Direction 	Method
> name 	"\u200Fפעילות הבינאום, W3C" 	Right-to-Left 	Bidi Control Character

Not a good example, since the first strong character would give the right result already. You could use this example: `\u200FHTML היא שפת סימון`. 

> name 	"\u200Eפעילות הבינאום, W3C" 	Left-to-Right 	Bidi Control Character

For this example you could use: `\u200E'سلام' is hello in Persian.`

> name 	"פעילות הבינאום, W3C" 	Right-to-Left 	First strong directional character
> name 	"The document was titled, 'פעילות הבינאום, W3C'" 	Left-to-Right 	First strong directional character

There's an additional issue in the row above, since the stuff between single quotes needs to have the baseline changed to RTL. You have two options:

1. without markup: "`The document was titled, '\u2067פעילות הבינאום, W3C\u2069'`" (although actually  \u2067...\u2069 (isolation) codes are not yet widely supported)

2. with markup: "`The document was titled, '<cite dir="rtl">פעילות הבינאום, W3C</cite>'`"

Choose whichever you want, but you ought to include the extra baseline definition.  It's not a bad idea to show inline baseline changes, but it might confuse the issue a little here.  Alternatively, you could use a different example, such as: "`The word for hello is 'سلام'.`"

> summary 	`<p dir=\"rtl\">פעילות הבינאום, W3C</p>` 	Right-to-Left 	HTML Markup

Since the first strong character is already RTL in this example, you'd get the same result by skipping the markup, so it's not that clear that consumers have to take the markup into account, rather than skipping the markup.  

Perhaps a better example would be: `<p dir=\"rtl\">HTML היא שפת סימון</p>`

That example starts with a LTR strong character, and forces the consumer to use the `dir` attribute to get the base direction right. (i presume that you are saying that the consumer needs to use markup if directional information is included? Otherwise, things could get a little messy wrt how to interpret the base direction.)

> summary 	`<p>פעילות הבינאום, W3C</p>` 	Right-to-Left 	First strong directional character (ignoring markup)
> 
> When producing an Activity Streams 2.0 document that contains bidirectional text, publishers SHOULD explicitly identify the default direction of any natural language value either by prefixing the value with a Unicode bidirectional control character or by using appropriate HTML markup, where permitted.

Again, i think the prefixing is only needed when the base direction cannot be correctly identified from the first strong character or the markup.

> Consumers of Activity Streams 2.0 documents that contain bidirectional text MUST use the Unicode Bidirectional Algorithm [[!BIDI]] to determine the appropriate rendering and display of natural language values.

Well, actually, we're saying that, in addition to using the bidi algorithm, they should use markup where provided, and we are encouraging them to use the first strong character heuristics to determine the overall direction (which is not required by the bidi algorithm).

hope that helps

**Comment by jasnell** [comment]
Updated the PR based on the feedback! Thank you!

**Comment by r12a** [comment]
editorial comments:

> SHOULD identify the base direction of any given Natural Language Value by either scanning the text for the first strongly directed character not contained within a markup element; or by utilizing directional markup or Unicode control characters where provided.

i think the text "or Unicode control characters where provided" is not needed, since they would be spotted by "scanning the text for the first strongly directed character not contained within a markup element".  So i suggest using just "or by utilizing directional markup where provided".

> the first strongly directed character

sounds a bit odd. The Unicode Standard says that these are called 'strong directional characters' (p173), so i suggest we say "the first strong directional character'.

**Comment by r12a** [comment]
> Once the base direction has been identified, consumers MUST use the Unicode Bidirectional Algorithm [[!BIDI]] to determine the appropriate rendering and display of natural language values.

i think this may need to be teased out just a little further. How about:

"Once the base direction has been identified, consumers MUST determine the appropriate rendering and display of natural language values, according to the Unicode Bidirectional Algorithm [[!BIDI]]. This may necessitate wrapping additional control characters or markup around the string prior to display, in order to apply the base direction."

**Comment by jasnell** [comment]
@r12a ... updated again! Thank you for the feedback :-)

**Comment by BigBlueHat** [comment]
Wanted to share some related research which I've noted on [the similar Annotation issue](https://github.com/w3c/web-annotation/issues/335#issuecomment-242156946).

It seems [Web App Manifest](https://www.w3.org/TR/appmanifest/) contains both [`dir`](https://www.w3.org/TR/appmanifest/#dir-member) and [`lang`](https://www.w3.org/TR/appmanifest/#lang-member) properties which govern it's inline strings.

Similar aims at least. :smile:

**Comment by r12a** [comment]
editorial nit: 

> scanning the text for the first strong directional character not contained within a markup element

should probably say 'markup tag', since it's only the tags we want to ignore.

and another:

apropriate -> appropriate

**Comment by r12a** [comment]
Just waiting for a response to the editorial suggestions just above. Otherwise ready to close this.
