### ISSUE TITLE
Spanish translations

### ISSUE THREAD

**Issue by r12a** [w3c/activitystreams#337]
Please Indicate One: 
 * [x] Editorial
 * [ ] Question
 * [ ] Feedback
 * [ ] Blocking Issue
 * [ ] Non-Blocking Issue

The example at https://www.w3.org/TR/activitystreams-vocabulary/#dfn-content  but also other examples have the Spanish:

> "sp": "Una <i>simple</i> nota"

`sp` is not a valid BCP 47 subtag for Spanish. It should say `es`.

Furthermore, I think the Spanish would be better as 

`"es": "Una nota <i>sencilla</i>" `

(simple has a different meaning)

**Comment by r12a** [comment]
This additional point from a comment by Addison Phillips, send last October.

> Note that it might be helpful to show a language tag with more structure. For example, you should show a Simplified Chinese item with the tag "zh-Hans" or perhaps "zh-Hans-CN".

**Comment by r12a** [comment]
Thanks for adding the chinese example, but it should be translated as 
一段<i>简单的</i>笔记

In addition, it's not really good to use <i> here, especially for chinese (where it's not common to italicise due to the complexity of characters).  I'd suggest using <em> instead.  

(fwiw, if you're interested, we have some additional info about <i> and <b> and issues for localisation at https://www.w3.org/International/questions/qa-b-and-i-tags)

**Comment by r12a** [comment]
Afaict, the above comments about chinese translation and use of `i` tags have not been addressed.

**Comment by jasnell** [comment]
Agreed. The https://github.com/w3c/activitystreams/issues/337#issuecomment-231375986 comment has not yet been addressed.

**Comment by evanp** [comment]
I've updated the zh-Hans examples to use <em> and to use the translation provided above. @r12a it'd be great to get your feedback and if we're OK get this issue closed.

**Comment by r12a** [comment]
Comments left at https://github.com/w3c/activitystreams/commit/9eb3f616592395c8b946989b5aa54e29a3e52852 and https://github.com/w3c/activitystreams/commit/6b1fa4f7fd5f82c41aaa954ad88153bd2934bcf7

**Comment by evanp** [comment]
There are updated editors drafts that use <em> for emphasis and include the lost character.

**Comment by r12a** [comment]
hi @evanp, the latest editors draft looks good wrt chinese and em tags. Thanks.
