### ISSUE TITLE
The preview property is missing in the Properties list for the Link type.

### ISSUE THREAD

**Issue by rogersuen** [w3c/activitystreams#343]
Please Indicate One: 
 * [X] Editorial
 * [ ] Question
 * [ ] Feedback
 * [ ] Blocking Issue
 * [ ] Non-Blocking Issue

Please Describe the Issue:

In the Activity Vocabulary doc, the `preview` property is defined with the Domain `Link`|`Object`, but it's missing in the Properties list for the `Link` type.

See : https://www.w3.org/TR/activitystreams-vocabulary/#dfn-link

**Comment by jasnell** [comment]
+1 ... yes this should be fixed.

**Comment by evanp** [comment]
Thanks for noting this, @rogersuen ! It's now in the Github repo and will be in the editor's draft soon.
