### ISSUE TITLE
***Map terms should be listed in the Properties chapter for clarity

### ISSUE THREAD

**Issue by rogersuen** [w3c/activitystreams#344]
Please Indicate One: 
- [X] Editorial
- [ ] Question
- [ ] Feedback
- [ ] Blocking Issue
- [ ] Non-Blocking Issue

Please Describe the Issue:

As per https://www.w3.org/TR/activitystreams-core/#naturalLanguageValues:

> The Activity Vocabulary defines three properties that use natural language values: name, summary, and content. Accordingly, in the JSON serialization, the terms " name", "summary", and "content" represent the JSON string forms; and the terms " nameMap", "summaryMap", and " contentMap" for represent the object forms.

For clarity reason, should these three terms be included in the list of properties defined in the chapter https://www.w3.org/TR/activitystreams-vocabulary/#properties ?

**Comment by jasnell** [comment]
-1... the `*Map` terms are largely an artifact of the serialization and not the vocabulary. When processed using JSON-LD algorithms, the `summary` and `summaryMap` properties, for instance, each expand to to the `http://www.w3.org/ns/activitystreams#summary` property in the vocabulary. The `summary` and `summaryMap` properties, in other words, are simply two alternative serializations for the exact same `summary` property in the vocabulary. None of the `*Map` variants should appear in the vocabulary document at all.

**Comment by evanp** [comment]
@rogersuen can you live with that answer?

**Comment by evanp** [comment]
It's been several months without an answer, so I'm going to close this one.
