### ISSUE TITLE
"Note" should probably be "Document"?

### ISSUE THREAD

**Issue by cwebber** [w3c/activitystreams#345]
Please Indicate One: 
 * [ ] Editorial
 * [ ] Question
 * [ ] Feedback
 * [ ] Blocking Issue
 * [X] Non-Blocking Issue

Please Describe the Issue:
["Note"](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-note) is grouped with all the other "Document" definitions in the vocabulary document, but is listed as inheriting from Object.  Is this intentional?

It seems like a typo, but if it's intentional, I'm okay with leaving it as-is. Just making sure!

**Comment by jasnell** [comment]
This was intentional as `Note` is intended to represent smaller more transient types of things such as status updates whereas a `Document` is intended to be more structured / file oriented types of things. It's a subtle difference but I've found it to be worthwhile. I'm good either way tho.

**Comment by evanp** [comment]
@cwebber can you live with it not being a Document?

**Comment by cwebber** [comment]
I can live with it!
