### ISSUE TITLE
Can value of object property be a list?

### ISSUE THREAD

**Issue by rhiaro** [w3c/activitystreams#346]
Please Indicate One: 
 * [ ] Editorial
 * [x] Question
 * [ ] Feedback
 * [ ] Blocking Issue
 * [x] Non-Blocking Issue

Can an Activity have multiple values for the `object` property, or is it supposed to be one `object` per `Activity`? ie.

```
{
  "@type": "Add",
  "object": [ 
                "http://img.amy.gy/files/food/160203_cheesecake3.jpg",
                "http://img.amy.gy/files/food/160203_cheesecake4.jpg"
  ],
  "target": "http://img.amy.gy/food/"
}
```

vs.

```
{
  "@type": "Add",
  "object": "http://img.amy.gy/files/food/160203_cheesecake3.jpg",
  "target": "http://img.amy.gy/food/"
}
```

and

```
{
  "@type": "Add",
  "object": "http://img.amy.gy/files/food/160203_cheesecake4.jpg",
  "target": "http://img.amy.gy/food/"
}
```

Is one preferable/required over the other, or are they equivalent and it doesn't matter?

**Comment by jasnell** [comment]
Yes. The value of any property can be a list unless the term is explicitly marked as being functional in the vocab definition
