### ISSUE TITLE
Link with `subject`?

### ISSUE THREAD

**Issue by rhiaro** [w3c/activitystreams#347]
Please Indicate One: 
 * [ ] Editorial
 * [x] Question
 * [x] Feedback
 * [ ] Blocking Issue
 * [ ] Non-Blocking Issue

In modelling links between things (Articles, Notes) I find myself wanting to be able to point to both of the things being linked from the `Link` object. Right now I can do:

`Object -> Link -> href`

but I want:

`Object <- Link -> href`

Can we add `subject` as a property of `Link`? Or am I missing something?

**Comment by jasnell** [comment]
Use the rel property of the link. For instance...

```json
{
  "type": "Link",
  "rel": "subject",
  "href": "..."
}
```

**Comment by rhiaro** [comment]
I'm not sure how that helps. I want to go from say:

```
{
  "id": "http://example.com/thing",
  "object": {
    "type": "Link",
    "href": "http://example.com/other"
  }
}
```

to

```
{
    "id": "http://example.com/somelink",
    "type": "Link",
    "href": "http://example.com/other",
    "subject": "http://example.com/thing"
  }
```
 Whereby I have a `Link` object which points to both of the two things it's linking between.

**Comment by rhiaro** [comment]
Okay, I can use `Relationship` for this per #348
