### ISSUE TITLE
What should subject and object of Relationship be?

### ISSUE THREAD

**Issue by rhiaro** [w3c/activitystreams#348]
Please Indicate One: 
 * [x] Editorial
 * [x] Question
 * [ ] Feedback
 * [ ] Blocking Issue
 * [x] Non-Blocking Issue

The wording and examples around `Relationship` imply that both the `subject` and `object` should be peopleish things (`Actor`s?) - it says "individuals" - but there are no actual domain/range constraints listed to that effect. Can we clarify the wording to make it clear whether it's just for `Actor`s, or can be used to relate any two `Object`s? (the latter, any two `Object`s, is my preference, unless I can use `Link` for this instead, per #347).

**Comment by jasnell** [comment]
It's anything. A person can have a relationship with another person, or a group, or an organization, or an animal, etc. This was left open ended to avoid constraining impls needlessly

**Comment by rhiaro** [comment]
So just to confirm, I can use Relationship to model a connection between non-person-y objects like say documents?

**Comment by jasnell** [comment]
Yes... tho you'll want to be careful not to conflate a `Relationship` type of thing with a `Link`-with-a-rel type of thing.

**Comment by rhiaro** [comment]
Yes I agree, that's why I opened #347 as well... because `Relationship` is the 'shape' I want `Link` to be.

**Comment by jasnell** [comment]
`Relationship` is essentially a reified `Link`.

If I had something like:

```json
{
  "type": "Article",
  "id": "http://example.org/foo",
  "attributedTo": {
    "type": "Link",
    "href": "http://example.org/bar",
  }
}
```

I could potentially represent that equivalently using a `Relationship` like so:

```json
{
  "type": "Relationship",
  "subject": {
    "id": "http://example.org/bar"
  },
  "relationship": "http://www.w3.org/ns/activitystreams#attributedTo",
  "object": {
    "type": "Article",
    "id": "http://example.org/foo"
  }
}
```

The two examples are roughly the same meaning, with the `Relationship` being a more concrete way of expressing the concept. The `Link` approach is less formal and less verbose.

**Comment by rhiaro** [comment]
Great. I'll take that :D
