### ISSUE TITLE
Figures not rendering?

### ISSUE THREAD

**Issue by cwebber** [w3c/activitystreams#349]
Please Indicate One: 
 * [ ] Editorial
 * [ ] Question
 * [ ] Feedback
 * [ ] Blocking Issue
 * [X] Non-Blocking Issue

Please Describe the Issue:

While figures are rendering just fine on the [editor's draft](http://w3c.github.io/activitystreams/core/#collections), it appears that the figures are 404'ing on the [latest published version](https://www.w3.org/TR/activitystreams-core/#collections).

**Comment by rhiaro** [comment]
I fixed this for the latest CR version (spoiler: out tomorrow!)
