### ISSUE TITLE
orderedItems in numerous examples, despite being deprecated

### ISSUE THREAD

**Issue by cwebber** [w3c/activitystreams#350]
Please Indicate One: 
 * [ ] Editorial
 * [ ] Question
 * [ ] Feedback
 * [ ] Blocking Issue
 * [X] Non-Blocking Issue

Multiple examples in both core and vocab use the orderedItems property, which is deprecated.  Should be an easy fix.

**Comment by jasnell** [comment]
When was `orderedItems` deprecated? There is zero indication of that in the editor or working drafts and I can see absolutely no justification for deprecating it.

**Comment by cwebber** [comment]
Sorry, my bad.  In that case, there's a different issue: [orderedItems is not mentioned in the properties section](https://www.w3.org/TR/activitystreams-vocabulary/#properties).  I falsely assumed this meant it had been deprecated at some point and was thus legacy.

**Comment by jasnell** [comment]
It's not mentioned in the properties because in the jsonld context it maps to http://www.w3c.org/ns/activitystreams#items. It is similar to the *Map properties in that it is an artifact of the serialization rather than being a distinct property.

**Comment by cwebber** [comment]
Okay, as long as that's intentional, I'm fine with that then!
