### ISSUE TITLE
Avoid mixed-content error with JSON-LD context in HTTPS

### ISSUE THREAD

**Issue by csarven** [w3c/activitystreams#351]
Please Indicate One: 
- [X] Editorial
- [ ] Question
- [ ] Feedback
- [ ] Blocking Issue
- [ ] Non-Blocking Issue

Please Describe the Issue:

If a document is loaded over HTTPS, JSON-LD libraries are subject to getting the mixed-content error in the browser if `@context` uses HTTP: `https://www.w3.org/ns/activitystreams`

Perhaps change (especially the examples) to use `https://www.w3.org/ns/activitystreams` to avoid this possibility altogether.

**Comment by csarven** [comment]
There is an equivalent issue at https://github.com/w3c/web-annotation/issues/347

**Comment by evanp** [comment]
I'm going to mark this at-risk that we may also support HTTP

**Comment by evanp** [comment]
I've added in a note about whether we would use http-only. I'm not sure of what the use-case is. @jasnell any ideas? can we just drop http: and use https: for everything?

**Comment by jasnell** [comment]
https for everything is fine but... that would affect the @context URLs. It would mean that all context URLs would need to use `https:` or risk running into the same kind of mixed-content error.

**Comment by csarven** [comment]
See also https://github.com/w3c/web-annotation/issues/347#issuecomment-244121694

**Comment by evanp** [comment]
All the examples use the HTTPS URL now; it also resolves correctly. So I think this can be safely closed.
