### ISSUE TITLE
Activity on behalf of a user

### ISSUE THREAD

**Issue by aries1980** [w3c/activitystreams#355]
### Please Indicate One:
 * [ ] Editorial
 * [x] Question
 * [ ] Feedback
 * [ ] Blocking Issue
 * [ ] Non-Blocking Issue

### Please Describe the Issue:

Hi, I'm wondering what is the best way to annotate if an activity is made by on behalf of the user by an other user? Is it recommended to use the "generator" property?

e.g.
```
{
  "@context": "http://www.w3.org/ns/activitystreams",
  "name": "Sally deleted a note",
  "type": "Delete",
  "actor": {
    "type": "Person",
    "name": "Sally"
  },
  "object": "http://example.org/notes/1",
  "origin": {
    "type": "Collection",
    "name": "Sally's Notes"
  },
  "generator": {
    "type": "Person",
    "id": "http://example.org/user/123"
  }
}
```
Thank you,
Janos

**Comment by jasnell** [comment]
Can you provide a plain text example? That would be helpful in identifying the exact way to represent it

**Comment by aries1980** [comment]
@jasnell Sure. Maybe the example is wrong but I wanted to use the same example I found in the AS2 proposal.

So let's say Samuel is an admin in the system. This system has the unique feature for the admin to "log in as" the user, so they cloak the identity and performs some action, on behalf of the user.  Sally complained about she was unable to delete her notes “http://example.org/notes/1”, and received an error. Samuel wanted to check it to see and describe to the developers better how to replicate this error. So Samuel performed this action, he succeed, but we want to annotate this action was not actually performed by the account holder, Sally, but by Samuel, on behalf of Sally.

**Comment by jasnell** [comment]
Ok, that's what I suspected. The base vocabulary really does not have a clear way of representing this case. The `generator` field is really intended to identify the software used to generate the activity statement. The capture the semantic correctly, you'll likely need to come up with an extension... something like:

```json
{
  "@context": [
    "http://www.w3.org/ns/activitystreams",
    {"prov": "http://www.w3.org/ns/prov#"}
  ],
  "actor": {
    "id": "http://samuel.example.org",
    "prov:actedOnBehalfOf": "http://sally.example.org"
  },
  ...
}
```

The `prov:actedOnBehalfOf` property is part of the [W3C Provenance vocabulary](https://www.w3.org/ns/prov#actedOnBehalfOf)

**Comment by aries1980** [comment]
Thank you @jasnell !

BTW is this the right forum to ask such questions?

**Comment by jasnell** [comment]
No problem, and yes, this is fine for asking questions. Glad I could help.
