### ISSUE TITLE
Q: Activity type "Update" describe actual modifications

### ISSUE THREAD

**Issue by tiblu** [w3c/activitystreams#359]
Please Indicate One: 
 * [ ] Editorial
 * [X] Question
 * [ ] Feedback
 * [ ] Blocking Issue
 * [ ] Non-Blocking Issue

Please Describe the Issue:

How would you describe the actual modifications for activity type "Update" (https://www.w3.org/TR/activitystreams-vocabulary/#dfn-update)?

For example, how would you describe following activity: _Sally updated her note from "Test note" to "Grocery list"_

**Comment by jasnell** [comment]
Doing so would require the use of extensions. The vocabulary does not include terms for describing specific changes.

**Comment by tiblu** [comment]
Thank you for your answer. Is there a link for a good read about the extensions and what are the best practices?

**Comment by jasnell** [comment]
There are no currently designed extensions but it's not too difficult to come up with something. It's going to depend largely on the type of resource being modified. For instance, if the object in question is a JSON object, you could use the [JSON Patch](https://tools.ietf.org/html/rfc6902) format to describe the changes and come up with a new field to contain it:

```json
{
  "@context": [
    "http://www.w3.org/ns/activitystreams",
    {
      "changeset": "http://example.org/changeset",
    }
  ],
  "type": "Update",
  "actor": "http://joe@example.org",
  "object": {"type": "Note", "id": "http://example.org/notes/1"},
  "changeset": [
    {"op": "replace", "path": "/title", "value": "Grocery list"}
  ]
}
```

It's not a perfect match to your example but it's close. Note that the `@context` is used to effectively declare the extensions being used. Read up on [JSON-LD](https://www.w3.org/TR/json-ld/) to understand how that part works.

**Comment by jasnell** [comment]
Another alternative is to use the `result` property to describe the resulting note object... Something like:

```json
{
  "@context": "http://www.w3.org/ns/activitystreams",
  "type": "Update",
  "actor": "http://sally.example.org",
  "object": {
    "type": "Note",
    "id": "http://example.org/notes/1",
    "name": "Example note"
  },
  "result": {
    "type": "Note",
    "id": "http://example.org/notes/1",
    "name": "Grocery list"
  }
}
```

Here, the consumer would need to know to compare the `object` and the `result` objects in order to determine the specific changes between the two.

**Comment by tiblu** [comment]
Thank you very much for these examples! I think I got 2 very good answers and closing this issue.
