### ISSUE TITLE
Q: Activity - a reply to a comment which is related to a another object

### ISSUE THREAD

**Issue by tiblu** [w3c/activitystreams#360]
Please Indicate One: 
 * [ ] Editorial
 * [X] Question
 * [ ] Feedback
 * [ ] Blocking Issue
 * [ ] Non-Blocking Issue

Please Describe the Issue:

I'm trying to create an activity for statement 
_"**Tom** replied to **John's** comment **"John's comment text"** on blog post **"Blog post title"** saying "**Tom's reply to John's comment on the blog post"**_

What I have come up with is:

```
{
  "@context": "https://www.w3.org/ns/activitystreams",
  "type": "Create",
  "id": "e0b7f2d5-fce9-4a92-8114-c412a91efab9",
  "name": "User replied to User's Comment on BlogPost with a Comment",
  "actor": {
    "type": "Person",
    "id": "8118e5d7-5023-4409-939e-380885d5cf7a",
    "name": "Tom"
  },
  "object": {
    "type": "Comment",
    "id": "5f53fd20-7727-4620-855f-fe83adccf07b",
    "text": "Tom's reply to John's comment on the blog post"
  },
  "inReplyTo": {
    "type": "Comment",
    "id": "1ab6fc03-bf67-4b6e-8304-26b31ef57236",
    "text": "John's comment text"
  },
  "to": {
    "type": "Person",
    "id": "de9ee166-a04a-4f63-8136-8c69ff1dd319",
    "name": "John"
  },
  "target": {
    "type": "BlogPost",
    "id": "099f8a53-9077-4cf2-bffb-1814e4eb2ab0",
    "title": "Blog post title"
  }
}
```

* As the Comment is reply to another Persons Comment, ``to``(https://www.w3.org/TR/activitystreams-vocabulary/#dfn-to) references to the author of the ``inReplyTo`` (https://www.w3.org/TR/activitystreams-vocabulary/#dfn-inreplyto).
* As the reply (``object``) is also related to BlogPost, BlogPost is the ``target``.

Am I over-complicating this?  Also I'm not sure about the relations - should I somehow nest the BlogPost relation to Comment in the Comment ``object``? Same applies to other relations - Comment belongsTo BlogPost, Comment hasOne Person (author), Comment(reply) hasOne Comment (parent).

**Comment by jasnell** [comment]
That looks about right.

**Comment by tiblu** [comment]
Thanks again!
