### ISSUE TITLE
Inconsistent usage of "type" and "class"

### ISSUE THREAD

**Issue by strugee** [w3c/activitystreams#362]
Please Indicate One: 
- [X] Editorial
- [ ] Question
- [ ] Feedback
- [ ] Blocking Issue
- [ ] Non-Blocking Issue

Please Describe the Issue:

AFAICT the spec seems to use the term "class" as interchangeable with the far more common "type." It seems reasonable to assume that these are the same thing, but it's probably better to clarify anyway, as I'm not 100% sure if these terms really do refer to the same thing.

One example is the text at the very beginning of section 4. Model:

> The object types defined by the vocabulary are segmented into a set of seven core types and an extended set of Activity and Object types common to many social Web applications. The core classes include:

The text talks about "object types," but then refers to "core classes" which makes interpreting the meaning of the following list kinda hard.

**Comment by jasnell** [comment]
Noted and good point.
