### ISSUE TITLE
Various typos

### ISSUE THREAD

**Issue by strugee** [w3c/activitystreams#363]
Please Indicate One: 
- [x] Editorial
- [ ] Question
- [ ] Feedback
- [ ] Blocking Issue
- [ ] Non-Blocking Issue

Please Describe the Issue:

I've found several typos in the spec. In order (emphasis added to illustrate the differences):
1. Section 4 Model: "seven core types" should (AFAICT) be "**eight** core types," as that's how many items there are in the list. (This is my assumption; I can't actually tell because of #362)
2. Section 4.2 Link, just under Example 8, in the paragraph beginning with "RFC 5988": "In the JSON serialization, A single link relation..." should become "In the JSON serialization, **a** single link relation..."
3. Section 4.7 Natural Language Values, Example 18:  the indentation of the final `}` is inconsistent with the first `{` (or at least, it is in the print version)
4. Section 5.1 Support for Compact URIs, just below Example 24, in the paragraph beginning with "In JSON-LD, Compact URI expansion...": seems like `"type": "id"` should read `"@type": "id"`, based on the example above. I don't know enough about JSON-LD to know if this is an actual typo, but I thought I'd mention it just in case.
5. Same as 4., but with the next paragraph: `@id` should maybe become `id`, based on Example 24? Not sure.
6. Section 9.2.1 Implementations and Section 9.2.2 Consumers are normative and seem to be written to use MUST and MAY as keywords, but none of these words are actually capitalized. If this was intentional it's not a problem, I just thought I'd bring it up in case it wasn't.

**Comment by jasnell** [comment]
Thank you.

**Comment by evanp** [comment]
I've taken care of each of these typos. As far as I can tell 4-6 are intentional so I'm letting them stand as is.
