### ISSUE TITLE
Vague language on OrderedCollection type usage requirements

### ISSUE THREAD

**Issue by strugee** [w3c/activitystreams#365]
Please Indicate One: 
- [ ] Editorial
- [ ] Question
- [ ] Feedback
- [ ] Blocking Issue
- [X] Non-Blocking Issue

Please Describe the Issue:

Section 4.6 Collection states:

> The `OrderedCollection` type can be used to identify a Collection whose items are always ordered.

The requirements for using `OrderedCollection` here are ambiguous. "can" should be replaced either by MAY, SHOULD, or MUST.

The exact same issue exists a couple paragraphs down:

> As with `Collection` objects, the items within a `CollectionPage` might be ordered or unordered. The `OrderedCollectionPage` type can be used to identify a page whose items are strictly ordered.

Again, "can" should be replaced with MAY, SHOULD, or MUST.

**Comment by akuckartz** [comment]
:+1:

**Comment by jasnell** [comment]
Noted. thank you!

**Comment by strugee** [comment]
@jasnell sure. Thank _you_! :)
