### ISSUE TITLE
Language implies that OrderedCollection pages may not be OrderedCollectionPages

### ISSUE THREAD

**Issue by strugee** [w3c/activitystreams#366]
Please Indicate One: 
- [ ] Editorial
- [ ] Question
- [ ] Feedback
- [ ] Blocking Issue
- [X] Non-Blocking Issue

Please Describe the Issue:

The very end of 4.6.1 Collection Paging states:

> If the pages of an `OrderedCollection` are not instances of `OrderedCollectionPage`, an implementation will have no reliable means of reconstructing the appropriate ordering of items. 

This seems to imply that there are conditions in which the pages of an `OrderedCollection` might be something other than `OrderedCollectionPage`s, like e.g. `CollectionPage`s. However, the rest of the spec (and in particular, Figure 15) seems to say that this shouldn't ever happen. What gives? 

Is this sentence just pointing out a logical conclusion - i.e. if a noncompliant implementation creates an `OrderedCollection` with `CollectionPage` pages, obviously there's no way to determine the order? If that's the case, since this sentence is addressing what happens in a very specific case given the presence of a noncompliant implementation, I don't really see why this is important enough to include in the spec.

Or alternately, is this sentence normative, stating that if an `OrderedCollection` with `CollectionPage` pages is encountered implementations MUST NOT assume their items are ordered? If this is the case, the rest of the specification seems to imply that this won't happen, which is confusing.

**Comment by jasnell** [comment]
The intent is to not be overly prescriptive. Notice that very little of the spec says things like "Don't do this". If implementers come up with a reason to use non-ordered collection pages in an `OrderedCollection`, they are free to do so with the recognition that the results might be unreliable.

**Comment by strugee** [comment]
@jasnell makes sense. Perhaps this could be a bit clearer, though? E.g. you could put a note saying something similar to the above in the spec, or make `OrderedCollection`s having `OrderedCollectionPage` pages a SHOULD (not a MUST)?

**Comment by jasnell** [comment]
Noted! Thank you!
