### ISSUE TITLE
More clarity on the scope of of anti-XSS considerations

### ISSUE THREAD

**Issue by strugee** [w3c/activitystreams#367]
Please Indicate One: 
- [ ] Editorial
- [X] Question
- [ ] Feedback
- [ ] Blocking Issue
- [ ] Non-Blocking Issue

Please Describe the Issue:

Section 7 Security Considerations states:

> Consumers that re-emit ingested content to end-users MUST take reasonable measures if emitting ingested content to make sure potentially malicious ingested input is not re-emitted.

I'm not sure that I fully understand exactly what scope "Consumers that re-emit ingested content to end-users" implies. For example, in pump.io we do anti-XSS scrubbing on incoming ActivityStreams objects. (Of course, pump.io is still on AS1 so this is a violation of spec. Oh well.)

In an AS2 world, would the above scrubbing be a violation of spec? In a sense, it's re-emitting content to end users, but it's doing so _through_ another consumer - the pump.io client.

**Comment by jasnell** [comment]
No, in fact anti-XSS scrubbing is exactly what this language *wants*

**Comment by strugee** [comment]
@jasnell okay. So pump.io would _not_ be violating spec, then? Even though it's not _directly_ emitting content to users?

**Comment by jasnell** [comment]
yep!

**Comment by strugee** [comment]
Cool, thanks very much! I'm looking forward to (hopefully soon) switching over to AS2 :)

**Comment by strugee** [comment]
Feel free to close unless you want to clarify this in the text (or whatever)

**Comment by evanp** [comment]
Closing per poster
