### ISSUE TITLE
Not applicable reference to Section 4.6 in conformance criteria

### ISSUE THREAD

**Issue by strugee** [w3c/activitystreams#368]
Please Indicate One: 
- [X] Editorial
- [ ] Question
- [ ] Feedback
- [ ] Blocking Issue
- [ ] Non-Blocking Issue

Please Describe the Issue:

Section 9.1 Documents states:

> Conforming documents must not use features of JSON-LD or other serialization features disallowed in this specification, as in Section 4.6.

However, I can't find anything that mentions disallowed serialization features in Section 4.6. Typo?

**Comment by jasnell** [comment]
Not sure if Typo or just out of date. Originally the draft was a bit more prescriptive about what JSON-LD features should not be used. This can and should be cleaned up.

**Comment by strugee** [comment]
@evanp the only thing I see in section 2 that relates to the text in question is the bit about not using relative IRIs/URLs. That would be a serialization feature, not serialization feature***s*** as the text says - maybe needs some more rephrasing? Idk. Your choice :P
