### ISSUE TITLE
AS1 objects with a "post" verb and a target turn into `Add`, but then the Object is never `Create`d

### ISSUE THREAD

**Issue by strugee** [w3c/activitystreams#369]
Please Indicate One: 
 * [ ] Editorial
 * [ ] Question
 * [ ] Feedback
 * [ ] Blocking Issue
 * [X] Non-Blocking Issue

Please Describe the Issue:

Section B Deprecated ActivityStreams 1.0 Syntax states:

> When processing Activity Streams 1.0 documents and converting those into 2.0, implementations SHOULD treat instances of the " post" verb as equivalent to Create if there is no target property specified; and equivalent to Add if there is a target property specified. 

However, it seems that if an incoming AS1 object was processed using this rule, it would result in an AS2 document describing an Object that has been "added" to something, but never "created." I haven't read the entirety of the Activity Vocabulary yet (just the Add and Create Activities), so I'm not sure if this is just how things are supposed to be used - but it seems kind of nonsensical for something that hasn't been "created" to be "added" to something.

I'm sure the authors of AS2 have more implementation experience than me, so if you guys still think this is a good mapping, that's OK by me. Just thought I'd bring it up, just in case.

**Comment by jasnell** [comment]
Some things simply are never actually Created. They just Are.... Or at least, it is safe for such things to be assumed in many cases.

**Comment by strugee** [comment]
Okay, sounds good! Thanks.
