### ISSUE TITLE
Namespace(s) for extensions

### ISSUE THREAD

**Issue by sandhawke** [w3c/activitystreams#370]
Please Indicate One: 
 * [ ] Editorial
 * [ ] Question
 * [ ] Feedback
 * [ ] Blocking Issue
 * [x ] Non-Blocking Issue

Please Describe the Issue:

Do we want every extension to live it its own namespace, or can serious extensions be put into http://www.w3.org/ns/activitystreams?   If the latter, what is a sustainable process for deciding and managing that list of "serious extensions"?

Specific extension for which we need an answer by October 11: ActivityPub.

See #283 and, in general, schema.org and the CG that manages it. 

Proposal-1: the set of terms in the ns/activitystreams namespace will never, ever change.   Every extension will be put in its own namespace.   ActivityPub will use it's own namespace.

Proposal-2: we'll have a community group which decides when to add terms, and it will set a low bar for temporarily adding terms for incubation/experimentations.  Basically, terms will be added after a review period of maybe 14 days unless someone has a principled objection.  Until the CG gets off the ground, the WG can make these decisions.  With this option, ActivityPub will use the AS namespace.

**Comment by jasnell** [comment]
Given that there are still pieces marked at risk in the vocab, allowing for open extension at this point might be a bit premature. That said, I'm fine with proposal-2.

**Comment by cwebber** [comment]
Clarification: it's an append only namespace :)

**Comment by sandhawke** [comment]
RESOLVED: Accept Proposal-2 from https://github.com/w3c/activitystreams/issues/370, being clear we're committed to keeping stable things stable
