### ISSUE TITLE
Make sure namespace is up to date with spec 

### ISSUE THREAD

**Issue by rhiaro** [w3c/activitystreams#375]
* [x] take out `upstreamDuplicates` and `downstreamDuplicates`
* [ ] fix broken fragments
* [ ] make sure nothing is missing
* [ ] ..

**Comment by rhiaro** [comment]
I removed from the namespace the following terms that are not in the Vocab or Core TR docs:

* upstreamDuplicates
* downstreamDuplicates
* rating
* provider
* author
* attachments
* tags

@jasnell @evanp Are any of these erroneously missing?

**Comment by gobengo** [comment]
'attachments', 'tags', and 'author' were old AS1 terms we used quite a bit. It's useful to have them in the context for back compat. However, I think having them in the optional AS1 compatibility context is fine. So I made a PR for that.

**Comment by jasnell** [comment]
The whole reason they existed in the context was to allow AS1 docs to be more seamlessly parsed as if they were AS2 when using JSONLD processing but the changes that have been made since already make that largely impossible. Moving those to the compat context makes sense.

**Comment by evanp** [comment]
So, it looks like we've fixed these up. I'm going to close out this issue.
