### ISSUE TITLE
Context value as string, list or object

### ISSUE THREAD

**Issue by rhiaro** [w3c/activitystreams#377]
Please Indicate One: 
 * [ ] Editorial
 * [ ] Question
 * [ ] Feedback
 * [ ] Blocking Issue
 * [ ] Non-Blocking Issue

Consumers need to be able to find the @context and recognise a document as AS2 whether the @context value is a string, or inside a list or object. There are examples in the spec that imply this, but it might be worth making explicit.

I will take an action to review current text in spec and PR if I think there's a clarification needed.

**Comment by evanp** [comment]
'Implementations producing Activity Streams 2.0 documents should include a @context property with a value that includes a reference to the normative Activity Streams 2.0 JSON-LD @context definition using the URL " https://www.w3.org/ns/activitystreams". Implementations may use the alternative URL " http://www.w3.org/ns/activitystreams" instead. This can be done using a string, object, or array. Examples below.'
