### ISSUE TITLE
[vocabulary] Place accuracy in percent?

### ISSUE THREAD

**Issue by dolmen** [w3c/activitystreams#387]
* [ ] Editorial
 * [X] Question
 * [ ] Feedback
 * [ ] Blocking Issue
 * [ ] Non-Blocking Issue

About the [Place](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-place).[accuracy](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-accuracy) property of the Activity Stream vocabulary: how can I relate an accuracy in percent to a latitude and a longitude like in the example?
I'm absolutely not an expert in the domain. But a more common indicator of accuracy for lat/lon seems to be [the number of reliable decimal places](http://gis.stackexchange.com/a/8674) (which can be translated to a radius at the Earth surface). I don't see how I could transform a percent into a number of decimal places or a radius.

**Comment by evanp** [comment]
@jasnell I don't know the origin of this one. Any suggestions?

**Comment by jasnell** [comment]
If accuracy is kept, then it should use the more common precision measure

**Comment by gobengo** [comment]
The web geolocation API gives me accuracy, but it's in meters.
https://dev.w3.org/geo/api/spec-source.html#accuracy
https://developer.mozilla.org/en-US/docs/Web/API/Coordinates/accuracy

That is, it's the radius of 95% confidence level.

Together, the radius(=webGeolocation.coords.accuracy) and accuracy(=95 or omitted) properties can express what you get from this web api.

**Comment by dolmen** [comment]
So, if the `accuracy` property is relative to the `radius`, an `accuracy` property without `radius` property (like in example 112) is useless?

**Comment by gobengo** [comment]
@dolmen the spec as written says that accuracy also applies to altitude. So altitude + accuracy at least is an example where it would not be useless without radius.

**Comment by gobengo** [comment]
But FWIW when I just implemented a bit of this for https://distbin.com , I just omitted publishing accuracy that I get from the Geolocation API, since the 95% bit is a non-normative SHOULD in the web API. i.e. when my JavaScript gets the radius, lat, lon, I really have no idea what the accuracy percentage is. So I didn't publish as:accuracy

**Comment by dolmen** [comment]
Due to how GPS works accuracy for altitude is quite different from the horizontal accuracy. [This article](http://gpsinformation.net/main/altitude.htm) says: "Altitude error is specified to be 1.5 x Horizontal error specification".
So using the same `accuracy` for both `radius` and `altitude` doesn't seem right for a general location spec as a GPS source is very common.
