### ISSUE TITLE
first, last, current properties say domain=CollectionPage, but other parts of doc imply domain=Collection

### ISSUE THREAD

**Issue by gobengo** [w3c/activitystreams#390]
Check out the vocabulary doc for the 'first' property:
https://www.w3.org/TR/activitystreams-vocabulary/#dfn-first

It says: "Domain: CollectionPage". However, I think this should be "Domain: Collection". Here's why:

* The example for 'first' is on a Collection, not a CollectionPage
* The [Collection definitions](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-collection) lists 'first' in its properties. CollectionPage doesn't (except by way of it extending Collection).

The core document does have some slightly confusing text in ["Collection Paging"](https://www.w3.org/TR/activitystreams-core/#h-paging) about this:

> The CollectionPage type extends from the base Collection type and inherits all of it's properties. The following additional properties can also be specified: partOf | first | next | prev | last | current |

To me and @rhiaro , this implies that current, first, and last, can be "additional"ly applied to CollectionPage, but not Collection.

So here are the two proposals:

1. For first, last, current: Change Domain to Collection instead of CollectionPage
2. For the previously quoted text in the core document, change "partOf | first | next | prev | last | current |" to "partOf | next | prev |"

**Comment by gobengo** [comment]
Looks like that "Domain: CollectionPage" row was last touched by @jasnell 
https://github.com/w3c/activitystreams/blame/master/vocabulary/index.html#L3454

James, do you agree that proposal #1 makes sense?

**Comment by jasnell** [comment]
The 'first' property can appear on either a Collection or CollectionPage and always points to a CollectionPage.
