### ISSUE TITLE
What counts as an implementations for the CR Exit Criteria?

### ISSUE THREAD

**Issue by sandhawke** [w3c/activitystreams#392]
Please Indicate One: 
 * [ ] Editorial
 * [ ] Question
 * [ ] Feedback
 * [x ] Blocking Issue
 * [ ] Non-Blocking Issue

Please Describe the Issue:

During the last meeting, it became apparent that there are differing views about what should count as an implementation for the purposes of reach two implementations of each feature, to meet the CR Exit Criteria.

Those criteria:
 
  _For this specification to be advanced to Proposed Recommendation, there must be at least two independent implementations of each feature. Each of these features may be implemented by a different set of products and there is no requirement that all features be implemented by a single product. ...  For the purposes of evaluating exit criteria, software that ignores or passes through types or properties inapplicable to their domain have not implemented the type or property._
 -- from https://www.w3.org/TR/activitystreams-core/#exit-criteria
 

I think the view of "position 1" is that interoperability is paramount, so when we say two implementations we really mean two which produce data and two which consume data, so that there can be interoperability between the first set and the second set.

I think the view of "position 2" is that a plain English reading of the Exit Criteria doesn't say anything about that, and a data-producing-system is still an implementation, so we count both producers and consumer.

It currently looks like this will impact about a dozen vocabulary terms.  Those terms will become extensions instead of being part of the initial Recommendation, if we go with Position 1.  I've no idea if this difference will matter to anyone, so it may not matter how we decide this issue.

**Comment by gobengo** [comment]
+1 position 2. A plain English reading of the spec is the only reasonable way to interpret it. The exit criteria could have been changed (with a vote) any time over the last several years, but it wasn't.
If there are interpretations other than that plain English that folks want to codify, propose a change to the Exit Criteria text and put it to a vote.

While I think it's best for the process to entertain proposals and then vote, personally I find any notion that the exit criteria should be interpreted differently than they've been written [10 months](https://github.com/w3c/activitystreams/blame/master/core/index.html#L230) appalling, especially raised after CR and after the initial WG charter expiration.

**Comment by evanp** [comment]
@gobengo that's a fair point, but... I believe the group discussed the two-consumer, two-producer idea before. I don't remember if somehow it reached the level of a resolution and was passed (in which case the editors failed to include it in the Exit Criteria), or if it reached the level of a resolution and didn't pass, or if it never got to a resolution at all.

We've had a lot of meetings. Can someone find a resolution requiring this interpretation?

**Comment by gobengo** [comment]
@evanp 
[Here is at least a piece of that conversation](https://socialwg.indiewebcamp.com/irc/social/2016-01-12#t1452623722725). Barring votes and resolutions from another day, it looks like the stricter criteria never made it to a proposal.

[There were unanimous +1s for "RESOLVED: Our CR-Exit for AS2 will be: Each feature of AS2 must be used by at least two independent implementations"](https://socialwg.indiewebcamp.com/irc/social/2016-01-12#t1452624715549)

There may be logs from other days that I haven't seen.

**Comment by sandhawke** [comment]
To my memory that is the key discussion.   It was an awkward one, because Tantek had made it clear he had views, but then wasn't present, so I was doing my best to represent what I thought he wanted.   As I read that transcript, there was clear support for the lower bar and none for the higher bar (despite that fact that I'm scribed as saying the opposite), so in the end we agreed on the lower bar with a vague plan to try to also understand the pattern of usage and do something with that.

**Comment by sandhawke** [comment]
For the record, this ended up not mattering, as all terms that had any implementations happened to meet the higher bar.
