### ISSUE TITLE
Remove four normative values for "relationship"

### ISSUE THREAD

**Issue by evanp** [w3c/activitystreams#406]
Implementation reports have shown no implementations of this at-risk feature.

**Comment by gobengo** [comment]
Remove:
IsContact															
IsFollowedBy															
IsFollowing															
IsMember

But not 'Relationship'.

Right?

**Comment by evanp** [comment]
@gobengo thanks! I revised the title

**Comment by evanp** [comment]
I'll replace any examples that use these vocabulary terms with vocabulary from http://vocab.org/relationship/
