### ISSUE TITLE
Validator link is broken

### ISSUE THREAD

**Issue by VladimirAlexiev** [w3c/activitystreams#411]
Please Indicate One: 
 * [ ] Editorial
 * [ ] Question
 * [ ] Feedback
 * [ ] Blocking Issue
 * [x] Non-Blocking Issue

Please Describe the Issue:
http://w3c.github.io/activitystreams/core/ link Validator to https://as2.rocks/: not found

**Comment by evanp** [comment]
Fixed.

**Comment by pfefferle** [comment]
It is broken again!
