### ISSUE TITLE
attributedTo limitation / extension

### ISSUE THREAD

**Issue by cappelaere** [w3c/activitystreams#413]
Please Indicate One: 
 * [ ] Editorial
 * [ ] Question
 * [ ] Feedback
 * [ ] Blocking Issue
 * [x ] Non-Blocking Issue

Please Describe the Issue: 
attributedTo can point to an author but seems to be missing a few things that could be extended.
1- License Information
"license": {
    "name": "CC BY 2.0",
    "url": "https://creativecommons.org/licenses/by/2.0/"
}
2- If author has just created a derived product, we need to specify what it was derived from, license and source information. Something like:
"derivedFrom": [
    {
        "title": "original product I modified",
        "license" : {...},
        "type": "Person",
        "name": "Pat C",
        "source": {
            "url": "http://example.com/picture.jpeg"
         }
    },...
]

**Comment by evanp** [comment]
This probably makes sense to deal with as an extension using the [ccREL](https://www.w3.org/Submission/ccREL/) vocabulary. I'm going to close this issue, and suggest continuing the conversation on the wiki page https://www.w3.org/wiki/Activity_Streams_extensions
