### ISSUE TITLE
GeoJSON Object 

### ISSUE THREAD

**Issue by cappelaere** [w3c/activitystreams#414]
Please Indicate One: 
 * [ ] Editorial
 * [ ] Question
 * [ ] Feedback
 * [ ] Blocking Issue
 * [ x] Non-Blocking Issue

Please Describe the Issue:
Any chance we could have a GeoJSON object of type "Feature" with properties and geometry attributes.  This would be a great example for GIS application where users add/delete features.  I suppose that this could be done via a schema extension as well.  This could also streamline Place objects with location (lat/long) which could be represented as Point Features.

**Comment by akuckartz** [comment]
GeoJSON ist problematic regarding JSON-LD support. WKT might be an alternative.

**Comment by evanp** [comment]
This probably makes sense to deal with as an extension. The WG decided to close this and deal with it extension-wise.
