### ISSUE TITLE
Implementation notes -> Primer?

### ISSUE THREAD

**Issue by rhiaro** [w3c/activitystreams#417]
Please Indicate One: 
 * [x] Editorial

I was thinking vaguely about a Primer for AS2, and I realised [section 5 of Vocabulary](https://www.w3.org/TR/activitystreams-vocabulary/#notes) is very practically informative and primer-like. But it's kind of buried under the huge table of definitions. Perhaps we could consider:

1. Moving it *above* the definitions
2. Duplicating it on a webpage like w3.org/2017/04/social/as2-primer so it's findable by itself (without the weight of the vocab definitions)
3. Spinning it out into a proper Primer and publishing this as a WG Note.

I'd be happy to take care of 2 or 3 if folks think it's worthwhile. It's all non-normative content, so I think we could safely move it out without worrying our timeline.

**Comment by gobengo** [comment]
no need IMO. Close issue?

**Comment by evanp** [comment]
I don't think we could make this kind of change at this point. I don't see a problem with using that section as the core for a primer, but I don't think we can get rid of the section at this point.

**Comment by strugee** [comment]
@evanp it might be nice to publish a CG report that combined the AP tutorial with an AS2 primer, what do you think?

**Comment by evanp** [comment]
Coming back to this issue after 5 years, I think the best way to continue this primer work is with the W3C wiki. That will let us get started with the Implementation content as a seed for the Primer, but we can expand with more information as needed.

I created the page here https://www.w3.org/wiki/Activity_Streams/Primer and will work on copying over Section 5.
