### ISSUE TITLE
register media type with IANA

### ISSUE THREAD

**Issue by dissolve** [w3c/activitystreams#424]
Please Indicate One: 
 * [ ] Editorial
 * [ ] Question
 * [ ] Feedback
 * [ ] Blocking Issue
 * [x] Non-Blocking Issue

Please Describe the Issue:

I had thought this was handled previously, but it does not appear that application/activity+json was ever actually registered with IANA.
It is not listed here: http://www.iana.org/assignments/media-types/media-types.xhtml

There is a submission form linked from that page.

**Comment by gobengo** [comment]
I filled out the form. Should get a response back in a week.

**Comment by strugee** [comment]
Thanks @gobengo! Is there a way to track the progress publicly? I seem to recall the registry for HTML `rel=` values having a publicly archived list but I don't know if IANA is the same.

**Comment by gobengo** [comment]
Nope but they responded to me and also looped in W3C liaison. Still
waiting. I'll update next week.

**Comment by strugee** [comment]
Neat. I suspected as much but thought I would ask anyway.

**Comment by gobengo** [comment]
Amanda Barber at iana.org has notified me that the revised application I filed has been accepted:

"""
The IANA Services Operator has registered the following media type:

application/activity+json

Please see

http://www.iana.org/assignments/media-types
"""

We should now be able to resolve this issue.

/dance !

**Comment by evanp** [comment]
Looks like this is done.
