### ISSUE TITLE
Fix URL on repo homepage

### ISSUE THREAD

**Issue by strugee** [w3c/activitystreams#425]
Please Indicate One: 
 * [x] Editorial
 * [ ] Question
 * [ ] Feedback
 * [ ] Blocking Issue
 * [ ] Non-Blocking Issue

Please Describe the Issue:

The top of https://github.com/w3c/activitystreams says this is the "AS2 Editor's Drafts" next to the spec URL, but AS2 is a REC so we should probably change that.

**Comment by gobengo** [comment]
Even though there is a published rec, the master branch here still might lead it and be considered not-yet-published.

I don't think we should change that, otherwise I'd make a PR.
I think we should close this issue.

**Comment by evanp** [comment]
I think this is done.
