### ISSUE TITLE
Python ActivityPub server implementation

### ISSUE THREAD

**Issue by MineRobber9000** [w3c/activitystreams#427]
Please Indicate One: 
 * [X] Editorial
 * [X] Question
 * [ ] Feedback
 * [ ] Blocking Issue
 * [ ] Non-Blocking Issue

Please Describe the Issue:

Do any Python implementations of ActivityPub exist?

By this, I mean are there any basic implementation server projects in Python (reference implementations or not) that I could reference? I'm working on a simple social network as a hobby project and was wondering how it would be implemented. I'm also having trouble understanding the tutorial.

**Comment by strugee** [comment]
@MineRobber9000 this is the Activity_Streams_ issue tracker. Did you mean ActivityStreams or ActivityPub?

**Comment by MineRobber9000** [comment]
@strugee probably. this organizational system is confusing to me. where should I put this to get a good response? (i.e; where is the correct place to ask this question?)

**Comment by strugee** [comment]
@MineRobber9000 the [ActivityPub repo][] is probably a decent place, or you could pop into `#social` on `irc.w3.org` ([here's an introduction to IRC](https://www.w3.org/wiki/IRC) if you need it). There's also an XMPP room which is bridged with the IRC channel, i.e. messages sent in one will appear in the other: https://www.w3.org/wiki/Socialwg#IRC

You could also try the mailing list at public-socialweb-comments@w3.org, but that's much less active than the issue tracker and IRC and people might not see your questions.

Also, related - please feel free to file issues about any parts of the tutorial that are confusing. I'm sure @cwebber would love to get feedback and improve it :-)

 [ActivityPub repo]: https://github.com/w3c/activitypub

**Comment by jaywink** [comment]
> Do any Python implementations of ActivityPub exist?

Hey @MineRobber9000 . I have a federation protocol library in Python that currently supports Diaspora protocol and I want to add ActivityPub support for it, hopefully within a few months or so. If you want, check it out, it would be great to collaborate (ie not being the only consumer of the library ;)).

The library is at https://github.com/jaywink/federation

**Comment by cwebber** [comment]
@MineRobber9000 https://github.com/rowanlupton/smilodon is an ActivityPub WIP implementation written in Python btw!

**Comment by gobengo** [comment]
@MineRobber9000 has your question been answered? If so, will you resolve this issue?

**Comment by MineRobber9000** [comment]
@gobengo My question has indeed been answered. If anyone comes across this while Googling, I ended up using @rowanlupton's [pylodon](https://github.com/rowanlupton/pylodon).
