### ISSUE TITLE
Result predicate inconsistently described or applied

### ISSUE THREAD

**Issue by azaroth42** [w3c/activitystreams#430]
## Please Indicate One: 
 * [ ] Editorial
 * [x] Question
 * [ ] Feedback
 * [ ] Blocking Issue
 * [ ] Non-Blocking Issue

## Please Describe the Issue:

The definition of `result` says:
> Describes the result of the activity. For instance, if a particular action results in the creation of a new resource, the result property can be used to describe that new resource. [[source]](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-result)

However the example given for the Create activity uses `object` to reference the newly created resource.
> See: https://www.w3.org/TR/activitystreams-vocabulary/#dfn-create

`result` is not used in any of the defined activity types, and the definition implies it should be used where it isn't.

## Suggested Remediation

Deprecate `result` or better define when it should be used.

**Comment by gobengo** [comment]
"Create" activities, once processed, could also have a corresponding `result` whose value is a Link to any resources that were created as a result of processing the Create activity.

`object` and `result`, in that case, would have very similar values, but the `object` is like input data. If taking in that `object` results in saving it somewhere that results in a new resource/uri being created, then include that in `result`.

**Comment by evanp** [comment]
Example 148 has a much better `result` example.

**Comment by evanp** [comment]
I've captured this information on the Primer in the W3C wiki. Here's the text:

The [result](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-result) property definition says it "[d]escribes the result of the activity. For instance, if a particular action results in the creation of a new resource, the result property can be used to describe that new resource."

However, the result of a "[Create](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-create)" activity is typically represented in the "object" property.

Other examples in the Vocabulary document show "result" properties as by-products or indirect results of the activity. For example, the "Accept" activity in example 148 shows a list of additional activities that resulted from the acceptance.

In general, the "object" property should be used for Create, and the "result" property should be used for changes of state or indirect outcomes from an activity.
