### ISSUE TITLE
What to use if type property is allready used to describe something else related to object

### ISSUE THREAD

**Issue by ilmartyrk** [w3c/activitystreams#435]
Please Indicate One: 
 * [ ] Editorial
 * [x] Question
 * [ ] Feedback
 * [x] Blocking Issue
 * [ ] Non-Blocking Issue

Please Describe the Issue:

As I read from the standard, object property `type` should indicate to the classname of this current object and  `@type` to the URI of the definition of this object. But what would be the proper usecase if property `type` is already used to describe something else related to this object and there is no URI to refer to?

**Comment by gobengo** [comment]
I believe ActivityStreams does not define/depend on `@type`.

JSON-LD does. And AS says, if you want to be doing JSON-LD processing, you can treat `type` and `@type` the same.

I think if you had a `type` and `@type` on the same object, but with different values, from AS2 perspective `type` would be authoritative. `@type` would be meaningless/unused as its not in AS2.

JSON-LD processors really won't like that AS2, though. However, AS2 does not 'require' supporting JSON-LD.

**Comment by evanp** [comment]
There are three main options when there is a vocabulary conflict with AS2:

1. Use namespace prefixes
2. Define the term in the document context 
3. Use an alias

I documented these processes in the Activity Streams 2.0 Primer, here:

https://www.w3.org/wiki/Activity_Streams/Primer/Vocabulary_conflicts

Given that the question is answered, I'm closing this issue.
