### ISSUE TITLE
Inconsistencies between property domains and type properties

### ISSUE THREAD

**Issue by cjslep** [w3c/activitystreams#436]
Please Indicate One: 
 * [ ] Editorial
 * [ ] Question
 * [X] Feedback
 * [X] Blocking Issue
 * [ ] Non-Blocking Issue

Please Describe the Issue:

(I am splitting my email to the public-socialweb mailing list into separate issues, for background please see those emails).

This is ActivityStream vocabulary specific: https://www.w3.org/TR/activitystreams-vocabulary

The specification is inconsistent with itself:

- The "altitude" property has domain "Object" in Section 4, but the "Object" class does not list "altitude" as a property in Section 2.
- The "id" property has domain "Object" and "Link" in Section 4, but the "Object" and "Link" classes do not list "id" as a property in Section 2.
- The "type" property has domain "Object" and "Link" in Section 4, but the "Object" and "Link" classes do not list "type" as a property in Section 2.
- The "attributedTo" property has domain "Link" in Section 4, but the "Link" class does not list "attributedTo" as a property in Section 2.

**Comment by sebilasse** [comment]
underlying problem here

- "altitude" does only appear in "Place" or "location"
- _this is the same for_ "latitude", "longitude"
but
- the domain for "altitude" is currently "Object"
- the domain for "latitude", "longitude" is currently "Place"
but
- the domain for "location" is "Object"

**Comment by gobengo** [comment]
> so maybe the domain for "altitude" should be "Place"

that would make it more consistent.
But I think a better consistency would be to have `latitude`, `longitude`, and `altitude` all have domain: Object.
Esp considering that the range of `location` includes `Object`. Non-Place location values currently can't specify lat/long? IMO that's weird.

I disagree that this is a "Blocking Issue", but it is good feedback for an AS2.0.1

**Comment by evanp** [comment]
Based on this issue, I've updated the ERRATA document to include the information about `altitude` and `attributedTo`. 

https://github.com/w3c/activitystreams/blob/master/ERRATA.md

Because `id` and `type` are addressed in the Core document, I don't believe the lists of properties require them in Vocabulary.
