### ISSUE TITLE
`summary` not allowed on `Mention`

### ISSUE THREAD

**Issue by cjslep** [w3c/activitystreams#439]
Please Indicate One: 
 * [ ] Editorial
 * [ ] Question
 * [X] Feedback
 * [ ] Blocking Issue
 * [X] Non-Blocking Issue

Please Describe the Issue:

(I am splitting my email to the public-socialweb mailing list into separate issues, for background please see those emails).

This is ActivityStream vocabulary specific: https://www.w3.org/TR/activitystreams-vocabulary

1. Example 58 of the spec contains the following example for the Mention type:

```
{
  "@context": "https://www.w3.org/ns/activitystreams",
  "summary": "Mention of Joe by Carrie in her note",
  "type": "Mention",
  "href": "http://example.org/joe",
  "name": "Joe"
}
```

However, the presence of "summary" in this example is conflicting with the rest of the document. The domain of the "summary" property type is only "Object", supported by the "Object" type listing "summary" as a property while "Link" does not. Since "Mention" extends "Link" and not "Object", it does not inherit the "summary" property. Thus, there is a contradiction between this example and the specification.

2. Examples 79 & 80 both have the following snippets:

```
{
  "type": "Image",
  "name": "Note icon",
  "url": "http://example.org/note.png",
  "width": 16,
  "height": 16
}
```

However, the "width" and "height" properties both only have a domain of "Link". The "Image" type extends "Document" which extends "Object", none of which have neither the "width" nor "height" properties. So this is the same kind of conflict between specification and example as #1.

**Comment by evanp** [comment]
I caught the `Image` problem in a later issue, #467 , so I've renamed this issue.

**Comment by cjslep** [comment]
Thanks. In the future I will split out issues, a little mad at myself that you had to spend your own time tracking that down.

**Comment by TGNThump** [comment]
#467 and the accompanying merge doesn't actually fix Example 79, only Example 80.
