### ISSUE TITLE
Example 150: Latitude/Longitude are not xsd:float

### ISSUE THREAD

**Issue by cjslep** [w3c/activitystreams#446]
Please Indicate One: 
 * [ ] Editorial
 * [ ] Question
 * [X] Feedback
 * [ ] Blocking Issue
 * [X] Non-Blocking Issue

Please Describe the Issue:

In https://www.w3.org/TR/activitystreams-vocabulary, Example 150 is:

```
{
  "@context": "https://www.w3.org/ns/activitystreams",
  "type": "Place",
  "name": "San Francisco, CA",
  "longitude": "122.4167",
  "latitude": "37.7833"
}
```

However `"122.4167"` and `"37.7833"` are not `xsd:float` and conflict with other examples such as Examples 57, 88, 112, 113, 124, 125, 130, and 136. They should be `122.4167` and `37.7833` respectively.

**Comment by evanp** [comment]
I think this is covered in the ERRATA.md already, so I'm closing as a duplicate.
