### ISSUE TITLE
Unclear definition of 'current' in paged collections

### ISSUE THREAD

**Issue by aschrijver** [w3c/activitystreams#485]
Please Indicate One: 
 * [ ] Editorial
 * [ ] Question
 * [x] Feedback
 * [ ] Blocking Issue
 * [ ] Non-Blocking Issue

Please Describe the Issue in https://www.w3.org/TR/activitystreams-vocabulary:

- [Collection#current](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-current):

  - The description _"In a paged Collection, indicates the page that contains the most recently updated member items."_ is unclear to me
  - So this returns a list of the most recent updates, which is not really related to paging but rather the result of a filter query.
  - But given that it is part of a paged collection and `current` returns a CollectionPage or a Link (to a CollectionPage?) I presume the query is intended to be something like _"Give me the N most recently updated items"_, where N equals the page-size.
  - After all if the recent-items query was _"Give me the updates of the last hour"_ it could result in, say,  >1000 items being returned, which is a Collection in itself and does not fit a CollectionPage (if the result exceeds page size)

If `current` was consistent in its meaning and related to paging then:

- In a `Collection` current would contain the (unordered) first page of the full collection filtered by `updated` property
- In an `OrderedCollection` that is ordered by `updated` property, it would just return the first page

But if the other interpretation is also valid, then how can I convey the meaning of `current`? Is there a best practice? More in general this leads me to 2 questions for which I'll create separate issues:

- [How can I indicate how a Collection is filtered](https://github.com/w3c/activitystreams/issues/483) (i.e. which query criteria were applied to obtain it)?
- [How can I indicate how an OrderedCollection was ordered](https://github.com/w3c/activitystreams/issues/484) (the examples in the spec show different orderings).

**Comment by nightpool** [comment]
> The first, next, prev, last, and current properties are used to reference other CollectionPage instances that contain additional subsets of items from the parent collection.

Collection instances *may be ordered or unordered*. If you Collection is truly randomly ordered throughout it's entire paging then it doesn't make sense to specify this property.

But if your collection's *paging* is ordered while the items within are *not* (for example, if your collection was the result of a query like `?before=id&after=id` and your pagination increases along `id`, but no order was imposed during the serialization) then there are situations when it would make sense to specify this property.

But overall, for any given Collection, if there is no page that contains the "most recently updated items" then there is no reason to specify this property.

**Comment by aschrijver** [comment]
Hmm, yes. Thank you. I think I don't need a `current` property for now :)

**Comment by gobengo** [comment]
@aschrijver Do you have unresolved concerns on this open issue?

**Comment by aschrijver** [comment]
Personally, no. I will not use `current`. But overall I wonder whether a clearer explanation in the spec would be helpful. You can close, if you find that not the case.

**Comment by evanp** [comment]
@aschrijver I added a section to the primer page on Collections about this property to make it clearer.

https://www.w3.org/wiki/Activity_Streams/Primer/Collections#current_property

I think that resolves this issue, so I'll close it if you're satisfied.

**Comment by aschrijver** [comment]
Thank you @evanp. Yes, that is well described :+1:
