### ISSUE TITLE
Incorrect domain in altitude

### ISSUE THREAD

**Issue by joseprous** [w3c/activitystreams#487]
Please Indicate One: 
 * [ ] Editorial
 * [ ] Question
 * [x] Feedback
 * [ ] Blocking Issue
 * [ ] Non-Blocking Issue

Please Describe the Issue:
In https://www.w3.org/TR/activitystreams-vocabulary/#dfn-altitude the domain of altitude is Object but it should be Place

**Comment by gobengo** [comment]
What do you mean by 'should'?
I'm all for the expressiveness of allowing altitudes to be recorded on non-Place Objects.

**Comment by joseprous** [comment]
Place have the following properties: accuracy | altitude | latitude | longitude | radius | units 
Look at Latitude and Longitude for example both have domain Place

**Comment by aschrijver** [comment]
@joseprous has a point, as `altitude` is not allowed (or mentioned) on `Object`.

**Comment by gobengo** [comment]
https://github.com/w3c/activitystreams/issues/436#issuecomment-360318923

**Comment by joseprous** [comment]
I didn't see that issue, it's a duplicate then. But that issue was not resolved either.

**Comment by evanp** [comment]
That issue was resolved recently, so I'm closing this one.
