### ISSUE TITLE
https://w3c.github.io/activitystreams/vocabulary/ fails to load properly

### ISSUE THREAD

**Issue by GrosSacASac** [w3c/activitystreams#501]
https://w3c.github.io/activitystreams/vocabulary/

 * Editorial

Please Describe the Issue:

From the console
Blocked loading mixed active content “http://www.w3.org/Tools/respec/respec-w3c-common”
Blocked loading mixed active content “http://www.w3.org/scripts/nanotabs/0.9/nanotabs.js”

**Comment by sebilasse** [comment]
I do not know what this is but the official spec. is here 
https://www.w3.org/TR/activitystreams-vocabulary
