### ISSUE TITLE
Would it be possible to add a "payment" predicate to the vocabulary?

### ISSUE THREAD

**Issue by melvincarvalho** [w3c/activitystreams#503]
Please Indicate One: 
 * [ ] Editorial
 * [x] Question
 * [ ] Feedback
 * [ ] Blocking Issue
 * [ ] Non-Blocking Issue

Please Describe the Issue:

For example :  Alice created a presentation, and received a Payment for it.

The requirement would be domain : Activity and range : I guess anyURI or Object.

I realize the vocab is relatively static, so I can implement this downstream.  I just thought it might be nice to mention here in case there was interest upstream.

Good idea / bad idea / thoughts?

**Comment by cjslep** [comment]
ActivityStreams is flexible and can use any of the existing RDF vocabulary from, for example, schema.org.

I also know the ValueFlows folks are interested in representing economic transformations in an RDF ontology.

The quickest way would be to pick something sensible, stick something appropriate in `@context`, document it somewhere, and run with it. But you may want to talk to other implementors before doing so?

**Comment by melvincarvalho** [comment]
@cjslep thanks for the response!

I have chatted with a few developers on this topic and they say more or less the same thing as you did.

I have actually completed a prototype implementation now, and am just working out with term to use.  

I think in the interests of speed I will use my own payment term in the `@context`.  This issue was just to see if there were others interested in the payment + activity use case, who wanted to weigh in.

I'm happy if this issue is closed.  Perhaps I'll leave it open for a short period just in case.

**Comment by melvincarvalho** [comment]
Closing this.  Thanks for the feedback.  

Feel free to reopen if there is renewed interest in payments upstream, at some point.

FYI : I have added a payment type for activities in line with the Activity Streams extension features.  It uses a different payments vocabulary.  All is working really well so far.
