### ISSUE TITLE
actor-like type for conversations/discussions

### ISSUE THREAD

**Issue by BenLubar** [w3c/activitystreams#509]
Please Indicate One: 
 * ⬜️ Editorial
 * ⬜️ Question
 * ☑️ Feedback
 * ⬜️ Blocking Issue
 * ⬜️ Non-Blocking Issue

Please Describe the Issue:

Being able to follow a discussion rather than just a person would solve a lot of problems with mentions being (mis)used as a method of marking replies to a conversation. It would also mean that forums could represent categories as recursive discussions, allowing for an easy standardized way to follow both.

Related:

 * #476 is a property for discovering relationships between posts in a conversation

**Comment by nightpool** [comment]
I think the best resolution to this is on the ActivityPub side—there's no *ActivityStreams* reason that you can't Follow a non-Actor object, as far as I can see.

see also https://socialhub.activitypub.rocks/t/unresolved-issues-surrounding-follow-activities/114, "Following non-actor objects"

**Comment by BenLubar** [comment]
What object type would represent a grouping of other objects, though? `Group` is documented as representing a group of *people*, not content.

**Comment by BenLubar** [comment]
Oh, actually, it looks like `Collection` can support all the properties of `Object`, so that seems like the way forward.

**Comment by nightpool** [comment]
@BenLubar Collection is definitely possible, although I was thinking you could just follow the root Object and then that would indicate you'd be interested in all of its replies.... not sure what that would look like from a addressing perspective though.
