### ISSUE TITLE
Why no Request in addition to Offer ?

### ISSUE THREAD

**Issue by srosset81** [w3c/activitystreams#521]
## Type
 * [ ] Editorial
 * [ ] Question
 * [x] Feedback
 * [ ] Blocking Issue
 * [ ] Non-Blocking Issue

## Issue

In the ActivityStreams vocabulary spec, it is written:

> The Offers use case deals with activities involving offering one object to another. It can include, for instance, activities such as "Company A is offering a discount on purchase of Product Z to Sally", "Sally is offering to add a File to Folder A", etc.

To open the possibility of using ActivityStreams for classifieds or marketplace-like apps, couldn't we consider adding a `Request` activity, which would be the other side of `Offer` ?

`Offer` can be used in many cases but I feel `Request` can be more explicit. In the second example above ("Sally is offering to add a File to Folder A"), it is clearly a suggestion. But a `Request` would be more affirmative, and it would imply that an answer is expected.

## Background

We are writing an [event management app](https://github.com/assemblee-virtuelle/activitypods/tree/master/packages/events), where events are private by default and can only be seen by invitees. The organizser can give some invitees the right to invite their own contacts. We use the Offer activity in two cases:

- When the organiser wants to tell an invitee he has the right to invite his own contacts, he sends an activity of type: Offer > Invite > Event
- When an "inviter" (someone with the right to invite) wants the organizer to invite some of his contacts, we also use an activity of type: Offer > Invite > Event.

In the first case, `Offer` is appropriate because it is a suggestion ("Please invite your friends"). But in the second case, we feel that the `Request` verb could be more appropriate ("Alright, so you can invite John and Jill").

We also plan to write a classifieds app, where Requests and Offers would be central.

**Comment by sebilasse** [comment]
Is there a big difference to the `Question` Activity?

**Comment by srosset81** [comment]
Well, I think there is ! :-)

The `Question` activity is designed for polls. It is about choosing one or more answers.
https://www.w3.org/TR/activitystreams-vocabulary/#questions

The `Request` activity would be about asking an actor to **do something**. Like for example "I ask you to invite my friend to your party" (Request > Invite)

**Comment by sebilasse** [comment]
Who told you it is designed for polls. It was mastodon who decided to restrict it to polls.
In no way we should let mastodon overtake the protocol.

Saying it very clear: **A Question is a Question** (otherwise it would be named 'Poll') …
It can be a question, request _or_ poll.
If you would like to federate with @redaktor or huge European Publishing Houses:
**A Question is a Question**

- used with `oneOf` is a “Poll”
- used with `anyOf` is a “Request”
- used open is a “Question”

cc @evanp

**Comment by aschrijver** [comment]
Yes, a `Question` could be used for any type of inquiry. The question (no pun intended) is: Should it be used to model e.g. a `Request`?

(note that the original [activitystreams 1.0](https://github.com/activitystreams/activity-schema/blob/master/activity-schema.md) had way more activity-types, including `request`, and they have been deliberately culled in v2.0)

Imho there is a general problem in the AS/AP where everyone tries to map their own domain model to the 'social primitives' that are provided in AS-Core spec. This only works if there is a _broad common understanding_ of the semantic concept and heuristics that are modeled. Where that's not the case, some apps `Offer` may have completely different meaning than another apps `Offer` does. Same case where you use `Question` and an impl that Retrospring [might implement later on](https://github.com/Retrospring/retrospring/issues/395).

So, again imho, options are:

1. Implement using standard AS, if that is compatible to other common uses of these activities
2. Implement as AS/AP vocabulary extension to make it clear what domain the model refers to.

For 2) it need not be app-specific. There could be standardization on an Event Management domain. Problem with 2) is that proper ways and best-practices to define vocab extensions and for others to reuse them too, is very poorly defined.

**Comment by sebilasse** [comment]
In the meeting I had proposed a way to solve exactly this because the ActivityStreams inventors (James and Evan) wanted to have a possibility to _describe_ potential resulting actions to others.
But it was specified before AP, so today the default ActivityHandler would be an ActivityPub object …
The document is far from being ready (and we need to be careful to never publish anything which could have security implications done wrong), so I would be curious what @yuforium thinks of it. 

Anyway, the discussion by the time was here:
https://www.w3.org/wiki/Activity_Streams/Expanded_Vocabulary#Potential_Actions_attached_to_objects

**Comment by srosset81** [comment]
> What gave you the idea it is a Poll?
> Saying it very clear: **A Question is a Question** (otherwise it would be named 'Poll') …
> It can be a question, request _or_ poll.

IMO in English the difference between a Question or a Request is quite clear. A Request is somewhat directive: "Can you invite me to your event" ? While a question could be: "How many people do you expect at your event ?". Both are indeed questions, but they have very different goals.

The examples given here are quite clear: https://www.askdifference.com/question-vs-request/

I agree that the AS ontology is not supposed to handle everything. But since we already have an `Offer` activity, I wonder why we don't have the "opposite" `Request` activity. I give again the example used for `Offer` activities:

> The Offers use case deals with activities involving offering one object to another. It can include, for instance, activities such as "Company A is offering a discount on purchase of Product Z to Sally", "Sally is offering to add a File to Folder A", etc.

In a marketplace-type app, Sally could be "offering" objects she doesn't need anymore but she could also be "requesting" objects she needs. I don't see how `Question` could fit here.

**Comment by evanp** [comment]
One thing that came up during issue triage is that there isn't a clear symmetry between `Offer` and `Request`. Care should be taken in defining this extension not to confuse the two too much.

**Comment by markcellus** [comment]
> A good use case to consider is stock markets (or other markets). An "ask" is an `Offer` to sell something at a particular price, and a "bid" is an `Offer` to buy something at a particular price.

"ask" in this context seems like `Question`--not an `Offer`, unless I'm missing something.

**Comment by aschrijver** [comment]
Cross-reference: This issue mentioned in [FEP-0837: Federated Marketplace](https://socialhub.activitypub.rocks/t/fep-0837-federated-marketplace/3501/5) by @srosset81 in the context of considering a Valueflows `vf:Proposal` type.

**Comment by evanp** [comment]
Reviewed 28 Mar 2025; still no FEP except FEP-0837.
