### ISSUE TITLE
How to use and license files of this repo

### ISSUE THREAD

**Issue by Daniel-Abrecht** [w3c/activitystreams#527]
Please Indicate One: 
 * [ ] Editorial
 * [x] Question
 * [ ] Feedback
 * [ ] Blocking Issue
 * [ ] Non-Blocking Issue

Please Describe the Issue:

I would like to make use of the file https://github.com/w3c/activitystreams/blob/master/vocabulary/activitystreams2.owl for the purpose of generating classes in one of my projects, and I would like to include that file in said project.
I would appreciate it if you could tell me if and how I can correctly license this file in my projects.

**Comment by nightpool** [comment]
I am not a lawyer, but my understanding is that all files in this repo are provided under the W3C Document License https://www.w3.org/Consortium/Legal/2015/doc-license.

**Comment by Daniel-Abrecht** [comment]
Thank you, that seams like what I was looking for.
I'm not a lawyer either, and I'm not entirely sure what exactly applies in my case yet, but I think I'll be able to figure it out with this.
