### ISSUE TITLE
endpoints should be defined as either `@container: @id` or `@container: @nest`

### ISSUE THREAD

**Issue by trwnh** [w3c/activitystreams#536]
Please Indicate One: 
 * [ ] Editorial
 * [ ] Question
 * [x] Feedback
 * [ ] Blocking Issue
 * [ ] Non-Blocking Issue

Please Describe the Issue:

### Proposal

One of the following:

- `endpoints` should have `"@container": "@id"` defined, in order to declare its keys as IRIs.
- `endpoints` should have `"@container": "@nest"` defined, in order to declare its nesting as semantically irrelevant.

### Motivation

The semantics of `endpoints` are not fully captured at present. Are they properties of the actor which are shared server-wide, or are they an ID map? https://www.w3.org/TR/json-ld11/#node-identifier-indexing

(Tangentially, I am unsure if `"@type": "@id"` is appropriate on those endpoints, given that it seems to specifically signal node identifiers, and the endpoints are not nodes on a graph, they are endpoints. Perhaps something like `xsd:anyURI` or leaving it as the default `@value`? I might be wrong on this, unsure.)

**Comment by nightpool** [comment]
Is endpoints an ActivityStreams property? I thought it was defined in ActivityPub. If so, this is the wrong repo for this issue

**Comment by trwnh** [comment]
it's in the activitystreams context .jsonld, so i assumed this would be right repo. my apologies
