### ISSUE TITLE
orderedAttachment (and orderedTag?)

### ISSUE THREAD

**Issue by trwnh** [w3c/activitystreams#537]
Please Indicate One: 
 * [ ] Editorial
 * [ ] Question
 * [x] Feedback
 * [ ] Blocking Issue
 * [ ] Non-Blocking Issue

Please Describe the Issue:

### pitch

problem: sometimes you want to have attachments in a certain order, but `attachment` is an unordered set by default

solution: define `orderedAttachment` similar to `orderedItems`

```json
{
	"@context": [
		{
			"orderedAttachment": {
				"@id": "https://...",
				"@type": "@id",
				"@container": "@list"
			}
		},
		"https://www.w3.org/ns/activitystreams"
	]
}
```

i am unsure if `orderedTag` makes sense as `tag` is not used purely for "tags" in the categorization sense, but doubtless if tumblr or some tumblr-like implementation wanted to order their tags, they would have no way of doing so.

**Comment by trwnh** [comment]
The current option you propose would add more complexity for "plain JSON" implementations that don't understand LD. These implementations have no way to signal to each other that attachments, tags, etc. are ordered. If orderedItems can exist, and it does exist for this very reason, then I think it is worth considering which other properties might be explicitly defined as ordered.

It feels very inelegant to say "just pretend they're ordered" without making them actually ordered. You may as well do a breaking change and redefine them in the context document to be `@container: @list` in that case... which would close the door on any AS2 producers that did indeed intend an *unordered* set. Having an `orderedProperty` variant is a much cleaner way of handling this. Well, either that or requiring LD, but the latter would also be a breaking change and a controversial one at that.

**Comment by evanp** [comment]
@trwnh see #540 for how this will get resolved. If this is a feature you want, you should start with a FEP. Can you get that going?

**Comment by trwnh** [comment]
https://codeberg.org/fediverse/fep/pulls/110/files

**Comment by trwnh** [comment]
it has come to my attention (https://github.com/mastodon/mastodon/issues/25588#issuecomment-1607801356) that some implementations such as mastodon already author as2 documents where `attachment` and `tag` are forced to be arrays even when containing 1 or 0 values. given that implementations such as mastodon likewise assume these arrays to be ordered always, it seems like there is an argument to be made for not going with `orderedTag` and `orderedAttachment`, but instead changing the normative context to make these properties always ordered. caveat: as stated before, this closes the door on producers who wish to author explicitly *unordered* sets of attachments or tags.

**Comment by silverpill** [comment]
Are there any use cases where unordered set might be desirable?
Media attachments and key-value pairs in profiles are assumed to be ordered by many implementations (and users), so I'd support making `attachment` an ordered property.

**Comment by trwnh** [comment]
Unordered sets are often semantically more accurate, but that's about it, I think. It matters for RDF and RDF canonicalization but not much else off the top of my head.

**Comment by trwnh** [comment]
@melvincarvalho i meant using an ordered `@list` when in reality the order doesn't matter -- we are discussing the consequences of making a normative change to `attachment` and `tag`, versus defining a new `orderedAttachment` and `orderedTag` with the same `@id` but different `@container` (as is currently done for `orderedItems` being defined as as:items but with `@container: @list`)

**Comment by trwnh** [comment]
Generally, this question extends to the following properties in popular practice:

- `attachment` (order of attachments sometimes matters)
- `tag` (order of tags *can* matter, e.g. tumblr)
- `oneOf` (order of poll options often matters)
- `anyOf` (order of poll options often matters)

Per [SocialHub discussion](https://socialhub.activitypub.rocks/t/fep-a070-ordered-properties-for-plain-json-consumers/3345/3?u=trwnh), our options are, from least messy migration to most messy migration:

- 1: Manually override the term definition, per-document. This allows producers to opt into ordering for these properties, on a per-document basis. However, only LD-aware consumers will be able to tell the difference. (AS2 also forbids overriding AS2 terms, but consider this a willful violation.)

- 2: Make normative changes, for everyone. This changes the AS2 context to align more closely to what most producers are already doing or assuming, essentially opting into (1) for everyone. However, some old documents might no longer be valid, if they contain a single item rather than an array.

- 3: Use new `orderedX` properties. This removes the ambiguity completely, for both LD-aware and plain-JSON consumers; however, it requires plain-JSON consumers to check for the new `orderedX` properties, and this may result in producers duplicating information in both the unordered and ordered properties, which has unintended consequences for the LD representation.

For example, given the following:

```json
{
  "@context": [
    "https://www.w3.org/ns/activitystreams",
    {
      "orderedAttachment": {
        "@id": "as:attachment",
        "@type": "@id",
        "@container": "@list"
       }
    }
  ],
  "orderedAttachment": ["one", "two"],
  "attachment": ["one", "two"]
}
```

It expands into the following:

```json
[
  {
    "https://www.w3.org/ns/activitystreams#attachment": [
      {
        "@id": "one"
      },
      {
        "@id": "two"
      },
      {
        "@list": [
          {
            "@id": "one"
          },
          {
            "@id": "two"
          }
        ]
      }
    ]
  }
]
```

Compacting against only AS2 without the `orderedAttachment` extension results in this:

```json
{
  "@context": "https://www.w3.org/ns/activitystreams",
  "attachment": [
    "one",
    "two",
    {
      "@list": [
        "one",
        "two"
      ]
    }
  ]
}
```

- 4: Redefine these properties as collections. This allows the use of `ordereditems`. However, existing implementations will almost certainly be confused by this change. In some ways, this is a harder break than (3), but with cleaner results. Funnily enough, no changes are needed to the normative context, only to convention (although AS2-Vocab examples could be reworked).

**Comment by trwnh** [comment]
interestingly, another example comes to mind of when sometimes you *do* want unordered -- unordered poll options may be presented in random order, i.e. if the producer wishes them to be randomized (to reduce first-option bias)

**Comment by trwnh** [comment]
https://w3id.org/fep/a070

**Comment by evanp** [comment]
Based on review, this would make a good FEP. I'm closing, but this will stay in the list of needs-fep issues.

I'd say the best way to adopt this structure into AS2 is:

1. Make an extension using a FEP (with namespace and context and so on)
2. Get it implemented
3. Bring it into the main AS2 context using the extensions policy.

**Comment by trwnh** [comment]
https://github.com/w3c/json-ld-syntax/issues/121#issuecomment-462051437 points out that different semantic mappings should be represented by different terms, e.g. `items` vs `orderedItems`, or `content` vs `contentMap`.

> Rob Sanderson: this came out of the sealing discussion
> … timc notes that schema.org has properties that take either text or resource
> … should we be able to say that a property accepts either type A or type B but not type C
> Gregg Kellogg: schema.org should have different properties for differently-typed values
> Ivan Herman: not really practical for schema.org users
> Rob Sanderson: you can rep this in the instance doc itself, inline
> … I say close won’tfix because it is unambiguous but ugly
> Gregg Kellogg: e.g. if you have a property ‘author’ it could have values of many different types
> Rob Sanderson: validation is not JSON-LD’s job, just mapping
