### ISSUE TITLE
history

### ISSUE THREAD

**Issue by trwnh** [w3c/activitystreams#539]
Please Indicate One: 
 * [ ] Editorial
 * [ ] Question
 * [x] Feedback
 * [ ] Blocking Issue
 * [ ] Non-Blocking Issue

Please Describe the Issue:

In AS2-Core examples 18, 19, 32, we find collections representing the "history" of an object. Particularly in example 32, we see an object being Created, Updated, and Deleted.

However, there is no property dedicated to advertising such a collection.

I propose a `history` term be defined in the activitystreams.jsonld context document and added to the AS2-Vocab as well.

**Comment by evanp** [comment]
This is a very interesting and helpful idea. I think the process that we have outlined in the [AS2 extensibility](https://www.w3.org/TR/activitystreams-core/#extensibility):

1. Develop the structure in an external context document, perhaps using the [FEP](https://codeberg.org/fediverse/fep). Ideally, you should also notify the SocialCG of the ongoing.
2. Get the extension implemented in a number of software packages, preferably >1.
3. Once the extension is "popular", the SocialCG can vote whether or not to include its terms in the main activitystreams.jsonld context.

I would happily work on this FEP! It sounds really interesting.

**Comment by trwnh** [comment]
This could indeed be expressed in an FEP but there is the issue of namespacing. It would be nicer to have it be `https://www.w3.org/ne/activitystreams#history` instead of something like `https://w3id.org/fep/xxxx/history` -- although it should be possible at a later point to adopt it into the activitystreams context with an external id, similar to how inbox is actually `ldp:inbox`

**Comment by evanp** [comment]
@trwnh are we going to create a FEP for this? I think the best idea would be to keep this issue open until the FEP has been started.

**Comment by trwnh** [comment]
https://codeberg.org/fediverse/fep/pulls/112

**Comment by evanp** [comment]
Since the FEP has been created, let's mark this resolved.
