### ISSUE TITLE
Document policy for adding extension terms into the normative context

### ISSUE THREAD

**Issue by trwnh** [w3c/activitystreams#540]
Please Indicate One: 
 * [ ] Editorial
 * [x] Question
 * [ ] Feedback
 * [ ] Blocking Issue
 * [ ] Non-Blocking Issue

Please Describe the Issue:

For years, some of the earliest "extension properties" were initially defined inline as context overrides: https://docs.joinmastodon.org/spec/activitypub/#as

This includes terms like `Hashtag`, `sensitive`, `manuallyApprovesFollowers`, and `movedTo`, which were loosely defined in 2017/2018 but never formally adopted. Consequently, everyone just inlined them as context extensions and we all pretend that they're part of the activitystreams namespace and context despite not actually being in there.

Some official guidance on this would be appreciated:

- Do people have the authority to define whatever extension terms they want within the activitystreams namespace?
  - If yes: are there any guidelines to govern when this is or is not allowed? Can we determine a set of "best practices" for using the activitystreams namespace with permission?
  - If no: which namespace should they use instead? Can we provide a namespace for incubating extensions, or some path to adopting externally-defined terms within the normative activitystreams context?
- For historical terms like the ones mentioned above: can we work on defining some or all of them formally and officially within the SocialCG, then adding them to the normative context? (This depends partially on the answer to the previous point.)

**Comment by evanp** [comment]
So, I split out the question of the historical terms to #541 . On the issue triage call, I agreed to write a SocialCG note for how we manage extensions and getting them into the main context. I will try to have this done for the next CG meeting.

**Comment by evanp** [comment]
There's a draft here. https://w3c.github.io/activitystreams/draft-extensions-policy.html

**Comment by evanp** [comment]
There is now a draft report in the SocialCG, so I'm going to close this ticket. https://github.com/swicg/extensions-policy is the next step.
