### ISSUE TITLE
Add to criteria for "Process for Including Extensions in Activity Streams 2.0"?

### ISSUE THREAD

**Issue by torgo** [w3c/activitystreams#547]
Please Indicate One: 
 * [ ] Editorial
 * [ ] Question
 * [X] Feedback
 * [ ] Blocking Issue
 * [X] Non-Blocking Issue

Please Describe the Issue:

As discussed in the CG meeting today, would it make sense to add to the criteria anything around I18N, A11Y or security / privacy review? As an example, in TAG we ask people to fill in [this issue template](https://github.com/w3ctag/design-reviews/blob/main/.github/ISSUE_TEMPLATE/005-early-design-review.md) when they request a review. I'm not suggesting you need to do anything as heavy-weight as that, but something lighter weight around these topics might be appropriate.

**Comment by evanp** [comment]
@torgo so, I added a section to the criteria for doing security, privacy, a11y and i18n reviews.

**Comment by evanp** [comment]
The section was added a while ago; the doc is now in the swicg/extensions-policy repo. 

https://github.com/swicg/extensions-policy/commit/a7bf2cee748e47e801bca32ea5bc290bc830d283

I'm closing.
