### ISSUE TITLE
Questions about Proposed Extension Management Process

### ISSUE THREAD

**Issue by steve-bate** [w3c/activitystreams#552]
Please Indicate One: 
 * [ ] Editorial
 * [x] Question
 * [ ] Feedback
 * [ ] Blocking Issue
 * [ ] Non-Blocking Issue

Please Describe the Issue:

I could be wrong, but it appears that the proposed extension process is for both extensions to the normative AS2 context and for extensions that are not intended to be added to the normative context. The Process and Criteria sections seem to have information that applies to one or the other "tracks" or both. 

For example, I'm assuming voting is not required for an extension that won't be included in the normative context. Is that correct?

I have similar questions about the Criteria section. Do non-normative extensions require two implementations before they can be listed on the extension registry wiki page? My understanding is that anyone with a W3C account can edit that page. Is that correct?

Maybe it would be helpful to more clearly separate the process and criteria for candidate normative extensions versus other extensions.

**Comment by evanp** [comment]
Hey, @steve-bate . So, you ask:

> I could be wrong, but it appears that the proposed extension process is for both extensions to the normative AS2 context and for extensions that are not intended to be added to the normative context. 

That is not the intention. It's not up to the CG to make rules for any extension whatsoever -- that's the whole point of extensions! Anyone can make one.

The motivation section of the document says:

> This document describes the process and criteria for approving extensions for inclusion in the main Activity Streams 2.0 context document. 

However, I think we could make it clearer by starting the "Process" steps at step 4 ("propose for inclusion") to show that this is only about the process for getting an extension added to AS2.

The other steps previously could be (and are!) part of the Criteria. So, these are what need to have already happened before we consider them for inclusion.

I'll take this as a task for editing the document.
