### ISSUE TITLE
as:anyOf mislabeled as oneOf in OWL file?

### ISSUE THREAD

**Issue by ahouseholder** [w3c/activitystreams#556]
https://github.com/w3c/activitystreams/blob/5f093f2f9aa3ec68e51bad9a949628fa81017b11/vocabulary/activitystreams2.owl#L215-L231

The "oneOf" label in line 225 seems like it should be "anyOf".

This causes confusion when using [Protégé](https://protege.stanford.edu/) to manipulate the ontology because it uses the label instead of the URI for the object property in the GUI, which means that it appears that there are two `oneOf` properties, when in fact one of them is the `anyOf` property just labeled as `oneOf`.

**Comment by evanp** [comment]
Thanks for this report! During issue triage, we decided it made sense to start putting more effort into this OWL file. We've moved it to its own repository, where it will be managed. I've moved this issue to that repository. Can you follow up on that thread?

**Comment by ahouseholder** [comment]
So since #559 was reverted, it seems like this issue should be reopened here as it remains relevant to the current master branch https://github.com/w3c/activitystreams/blob/0ee7f65c24fd035ef32c9076bcff0dc399400322/vocabulary/activitystreams2.owl#L224-L226
