### ISSUE TITLE
LICENSE.md or LICENSE file missing from repository

### ISSUE THREAD

**Issue by ThisIsMissEm** [w3c/activitystreams#558]
Please Indicate One: 
 * [ ] Editorial
 * [ ] Question
 * [ ] Feedback
 * [x] Blocking Issue
 * [x] Non-Blocking Issue

Please Describe the Issue:

I just realised we don't actually have the W3C Document and Software License in this repository, and we should probably rectify that.

Related to: https://github.com/w3c/activitystreams/issues/527

**Comment by evanp** [comment]
I added a `LICENSE.md` to the repository using the W3C Software and Documentation license, 2015 version. We'll need to update this to the 2023 version at some point. I'll open a new issue for that.

**Comment by ThisIsMissEm** [comment]
LGTM

**Comment by evanp** [comment]
LGTM2
