### ISSUE TITLE
Add more extensive descriptions in the OWL ontology

### ISSUE THREAD

**Issue by cristianolongoodhl** [w3c/activitystreams#561]
Please Indicate One: 
 * [ ] Editorial
 * [ ] Question
 * [x] Feedback
 * [ ] Blocking Issue
 * [ ] Non-Blocking Issue

Please Describe the Issue:

The Activity Vocabulary specification is provided as a text document written in natural language. But, aside this, the vocabulary is also described in a non-normative OWL ontology.

Using OWL allows one reusing all the machineries which, during the years, have been developed in the Semantic
Web realm. This brings with it several advantages. First, the more detailed is the OWL vocabulary, the more it is a valuable guidance for software developers which has to deal with it; about this, one should also take into account all the software frameworks for the so called Ontology to Object mapping which foster using OWL defined classes and properties in object oriented software. Next, reasoning techniques developed in this context enable the automatic detection of logical  inconsistencies, which may be overlooked when specifications are provided in natural language. Moreover, reasoning engines can be effectively employed to infer implicit knowledge from a semantic web knowledge base.

All the aforementioned features are as more effective as more the descriptions in the OWL vocabulary are close to the official specification provided in natural language. However, at the time of writing the OWL version of the Activity Vocabulary mainly consists of the class hierarchy and the definition of properties in terms of domain and range.

I suggest that the definitions in the OWL ontology should be as extensive as possible in order to maximize the benefits listed above.

**Comment by trwnh** [comment]
If this gets pursued further, then I would suggest considering something related: certain types/classes/properties should be marked as equivalent to other vocabularies and ontologies where appropriate. For example:

```turtle
as:Person owl:equivalentClass vcard:Individual .
as:Group owl:equivalentClass vcard:Group .
as:Organization owl:equivalentClass vcard:Organization .
```

This would provide more support/hints to recommendations such as the one that says that VCard SHOULD be used to markup additional properties for the above types.

**Comment by cristianolongoodhl** [comment]
But for example, why vcard:Organization and not org:Organization? I suppose that such kind of mappings of course would be useful, but should be placed in its own documents.

**Comment by cristianolongoodhl** [comment]
I have to cite the [activity pub ontology from Steve Bate](https://github.com/steve-bate/activitypub-ontology), which may be a good starting point. In addition, some days ago I submitted the pull request #562 with extended definitions for Activity subclasses just to demostrate a bit.

**Comment by cristianolongoodhl** [comment]
see also #516 

Probably the resolution status of this may be changed to volountary needed

**Comment by evanp** [comment]
@cristianolongoodhl I appreciate the issue and especially the PR. However, the changes are probably too numerous for me to review and for us to have a discussion about them. Here is my proposed process for going forward:

1. We open issues specific to each of these OWL classes you want to change -- maybe 3 to 5 issues to start out, one issue per class.
2. We have discussions in the GitHub issues about the proposed change.
3. Based on the discussion, and perhaps a CG decision for more contentious ones, I could merge the PRs.
4. As this process improves, the chairs can pick an AS2 OWL editor to manage this process directly.

Does that sound right? Could you take the first 3 or so of your changes and make them separate PRs for us to discuss?

**Comment by cristianolongoodhl** [comment]
Dear Evan, I observe not so much interest about this in the group, may be because there are very few semantic web folks here. So probably would be better to submit these proposals to a Semantic Web conference and eventually come back here if and when the publication will be accepted. 
So with your permission I would just close the issue.

**Comment by cristianolongoodhl** [comment]
I published a novel ontology which extends activitystreams2.owl with the additional constraints I provided: [http://www.opendatahacklab.org/ns/as2extdefs](http://www.opendatahacklab.org/ns/as2extdefs).
