### ISSUE TITLE
Default units for Place Object

### ISSUE THREAD

**Issue by bobwyman** [w3c/activitystreams#581]
Please Indicate One: 
 * [ x] Editorial
 * [ ] Question
 * [ ] Feedback
 * [ ] Blocking Issue
 * [ ] Non-Blocking Issue

Please Describe the Issue:

The [Place Object](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-place)  allows the provision of a ```unit```, which presumably modifies the interpretation of its ```altitude``` field. However, this relationship is not specified in the text and no default unit is provided.

I suggest the need for a ```Place``` primer topic stating that ```unit``` modifies ```altitude.``` If producers provide an ```altitude```, then ```unit``` is a required field and must be provided. If no ```altitude``` is provided, ```unit``` must not appear. However, if ```altitude``` is provided without a ```unit```, readers may assume the default value ```meters.```

It should also be stated that ```altitude``` should be interpreted as distance above, or below, mean sea level on Earth rather than distance relative to the surface at the given latitude/longitude or any other point. (Note: This assumption, while appropriate for altitudes on Earth, would not apply on non-Earth bodies that typically have no "sea-level.")

Finally, I suggest that it be stated that ```latitude```, ```longitude```, and ```altitude```, as defined in the current version of the vocabulary, apply only to places which are on the planet Earth. And, it would be useful to clarify that the coordinate reference system for ```latitude``` and ```longitude``` is EPSG:4326; the EPSG code for WGS84.

Note: I am preparing a FEP to define an extension defining a new ```crs``` field that would provide for specification of the coordination reference system to be used in interpreting these values. This extension would allow the use of alternative CRS's on Earth as well as extend the use of ```Place``` to the description of locations on non-Earth bodies.

**Comment by evanp** [comment]
I think this makes a lot of sense. We created https://www.w3.org/wiki/Activity_Streams/Primer/Place_type in issue triage; please review and update as necessary.

**Comment by evanp** [comment]
I've transferred this to the swicg/geosocial task force for review. It'd be good to work on more specific Place properties there.
