### ISSUE TITLE
Difference between @type/@id in JSON-LD and type/id in AcitivtyStream

### ISSUE THREAD

**Issue by Mihailoff** [w3c/activitystreams#592]
Please Indicate One: 
 * [ ] Editorial
 * [x] Question
 * [x] Feedback
 * [ ] Blocking Issue
 * [ ] Non-Blocking Issue

Please Describe the Issue:

I'm new to ActivityStreams and was actively studying it for a couple of days.

It seems that the purpose of the `type` and `id` in AcitivtyStream is pretty similar if not the same as `@type` and `@id` in JSON-LD.

For example, in https://www.markus-lanthaler.com/hydra/spec/latest/core/ spec `@type` and `@id` is used "as-is" conforming to the `JSON-LD` definition.

I could not find the definition of `type` and `id` properties in specs https://www.w3.org/ns/activitystreams/ https://www.w3.org/TR/activitystreams-core/ https://www.w3.org/TR/activitystreams-vocabulary/

It makes it confusing. In this regard, using `@type` and `@id` in AS would reduce the learning curve and perhaps the adoption.

**Comment by nightpool** [comment]
"type" and "id" are defined in the JSON-LD context document to be pure aliases of the JSON-LD `@type` and `@id` properties: https://www.w3.org/ns/activitystreams

They were created purely to make it so consumers using languages like Javascript, Typescript and others that use the `.` notation for access properties could more easily access the type and id of activitystreams objects. So, for example, you can do `post.id` in javascript without having to add some complicated manual conversion layer or litter your code with hundreds of `post["@id"]` sigils.

**Comment by Mihailoff** [comment]
The only mention I found is this https://www.w3.org/ns/activitystreams.jsonld suggesting that it is an alias?

```
{
  "@context": {
    "@vocab": "_:",
    ...
    "id": "@id",
    "type": "@type",
}
```

Will this be a valid AS statement?

```JSON
{
  "@context": "https://www.w3.org/ns/activitystreams",
  "@type": "Object",
  "@id": "http://www.test.example/object/1",
  "name": "A Simple, non-specific object"
}
```

**Comment by Mihailoff** [comment]
> They were created solely to make it so consumers using languages like Javascript and others that use the . notation for property access could more easily access the type and id of activitystreams objects. So, for example, you can do post.id in js without having to add some complicated manual conversion layer or litter your code with hundreds of post["@id"] sigils.

Thank you. This explains it.

---

`$id` and `$type` could work for easy JSON access but could potentially create issues on the storage query side. In some databases `$` is a special character...

```JS
const test = {
  "$id": "hi"
}

console.log(test.$id) // 'hi'
```

The safest is `_` but it is now drifted away from `JSON-LD`.

To conclude: it is what it is and for a reason. I hope this will be a valuable piece of knowledge for others.
