### ISSUE TITLE
The vocabulary definition does not agree with the spec

### ISSUE THREAD

**Issue by MPvHarmelen** [w3c/activitystreams#599]
The following two lines define the `as` prefix with `http`:

https://github.com/w3c/activitystreams/blob/e02b87b3ca4abb5b546f4c1ad92b1f357d202bfd/vocabulary/activitystreams2.owl#L1-L2

while [the spec](https://www.w3.org/TR/activitystreams-vocabulary/#h-types) defines it with `https`:
> Base URI: `https://www.w3.org/ns/activitystreams#`.

Since the spec has already been published, I suggest changing the vocabulary file to use `https` too.

**Comment by csarven** [comment]
I suggest closing this issue to keep discussion around it to minimal. There had been other issues already on this. It is potentially resolved by https://github.com/w3c/activitystreams/pull/504 . See also https://github.com/w3c/activitystreams/issues/416#issuecomment-1847543536

**Comment by MPvHarmelen** [comment]
Closed in favour of #504
