### ISSUE TITLE
sparql service for activitystreams2 ontology

### ISSUE THREAD

**Issue by phtyson** [w3c/activitystreams#603]
Please Indicate One: 
 * [ ] Editorial
 * [x] Question
 * [ ] Feedback
 * [ ] Blocking Issue
 * [ ] Non-Blocking Issue

Is there an official SPARQL endpoint that will answer to federated queries about the ActivityStreams2 ontology?

Does W3C host such services, and if so what does it take to set one up?

**Comment by csarven** [comment]
There is no such SPARQL endpoint to the best of my knowledge.

I don't speak for W3C but I doubt they'll set it up. Hard to say what it would take for W3C to set it up ;)

Not sure why you would need this but perhaps https://sparql.org/sparql.html is of some interest. It is not associated with W3C. It is a free as is service.

Allows `SELECT` and `CONSTRUCT`, e.g.:

https://sparql.org/sparql?query=SELECT+*%0D%0AFROM+%3Chttp%3A%2F%2Fwww.w3.org%2Fns%2Factivitystreams-owl%3E%0D%0AWHERE+%7B%0D%0A%3Fs+%3Fp+%3Fo+.%0D%0A%7D&default-graph-uri=&output=xml&stylesheet=%2Fxml-to-html.xsl

```
SELECT *
FROM <http://www.w3.org/ns/activitystreams-owl>
WHERE {
?s ?p ?o .
}
```

Allows `SERVICE` too (IIRC).

**Comment by phtyson** [comment]
`http://www.w3.org/ns/activitystreams-owl` would work fine if it returned a correct document (#504 ). I tried it in a SERVICE federated query for the purpose of getting AS2 class and property declarations without having to import them in my local dataset.

**Comment by TallTed** [comment]
All things considered, especially given https://github.com/w3c/activitystreams/pull/504, I would recommend you just load the ontology into your local dataset.

**Comment by phtyson** [comment]
> All things considered, especially given #504, I would recommend you just load the ontology into your local dataset.

Yes, that is what I am doing for now, but as I anticipate having several local datasets supporting different webapps, that is not ideal. Longer-term, I'll set up my own sparql service from which the others can get schema info.

**Comment by phtyson** [comment]
If either https://github.com/w3c/activitystreams/issues/606#issuecomment-2239616808 or https://github.com/w3c/activitystreams/issues/606#issuecomment-2240877468 were implemented, it would meet the need.

**Comment by phtyson** [comment]
question answered, possible resolution in #606
