### ISSUE TITLE
wrong activitystreams namespace in activitystreams2 ontology

### ISSUE THREAD

**Issue by phtyson** [w3c/activitystreams#604]
Please Indicate One: 
 * [ ] Editorial
 * [ ] Question
 * [ ] Feedback
 * [x] Blocking Issue
 * [ ] Non-Blocking Issue

In activitystreams2.owl:
1. change `@prefix as: <http://www.w3.org/ns/activitystreams#> .` to `@prefix as: <https://www.w3.org/ns/activitystreams#> .`. ([Activity Vocabulary](https://www.w3.org/TR/activitystreams-vocabulary/#types))
2. remove unneeded empty prefix
3.  remove unneeded `@base` directive

I have updated this in my fork, will submit pull request soon.

The ontology URI is `<http://www.w3.org/ns/activitystreams#> ` but I will defer to project leads whether to change that.

**Comment by csarven** [comment]
I suggest closing this issue to keep discussion around it to minimal. There had been other issues already on this. It is potentially resolved by https://github.com/w3c/activitystreams/pull/504 . See also https://github.com/w3c/activitystreams/issues/416#issuecomment-1847543536

**Comment by phtyson** [comment]
Closed as duplicate

**Comment by phtyson** [comment]
Closing as duplicate of #504
