### ISSUE TITLE
How do I resolve the `@context` property in the root if it's an array?

### ISSUE THREAD

**Issue by KisaragiEffective** [w3c/activitystreams#611]
Please Indicate One: 
 * [ ] Editorial
 * [x] Question
 * [ ] Feedback
 * [ ] Blocking Issue
 * [ ] Non-Blocking Issue

Please Describe the Issue:

ActivityStreams 2.0 is backed by JSON-LD, but AS2's `@context` is able to be an array.
This is different from JSON-LD, right?
I can't see how I (or implementor) should resolve it. 
For example, take look at:

```jsonc
{
  "@context": [
    "https://www.w3.org/ns/activitystreams",
    "https://w3id.org/security/v1",
    {
      "Key": "sec:Key",
      "manuallyApprovesFollowers": "as:manuallyApprovesFollowers",
      "sensitive": "as:sensitive",
      "Hashtag": "as:Hashtag",
      "quoteUrl": "as:quoteUrl",
      /* and so on ... */
    }
  ],
  "id": /* URI that refers activity */,
  "actor": /* user */,
  "type": "Create",
  "published": "2024-08-11T21:11:02.551Z",
  "object": {
      "type": "Note",
      /* whatever */
  },
  "to": [
    "https://www.w3.org/ns/activitystreams#Public"
  ],
  "cc": [
    // followers
  ]
}
```

**Comment by nightpool** [comment]
No, this is standard JSON-LD, there's nothing unique to AD2 here. If you want to implement JSON-LD, I recommend you use an existing library.

Most people are better served by just ignoring the context though

**Comment by nightpool** [comment]
For reference, here is the relevant JSON-LD term definition:

> [embedded context](https://www.w3.org/TR/json-ld11/#dfn-embedded-context):
> An embedded [context](https://www.w3.org/TR/json-ld11/#dfn-context) is a context which appears as the @context [entry](https://infra.spec.whatwg.org/#map-entry) of one of the following: a [node object](https://www.w3.org/TR/json-ld11/#dfn-node-object), a [value object](https://www.w3.org/TR/json-ld11/#dfn-value-object), a [graph object](https://www.w3.org/TR/json-ld11/#dfn-graph-object), a [list object](https://www.w3.org/TR/json-ld11/#dfn-list-object), a [set object](https://www.w3.org/TR/json-ld11/#dfn-set-object), the value of a [nested properties](https://www.w3.org/TR/json-ld11/#dfn-nested-property), or the value of an [expanded term definition](https://www.w3.org/TR/json-ld11/#dfn-expanded-term-definition). Its value may be a [map](https://infra.spec.whatwg.org/#ordered-map) for a [context definition](https://www.w3.org/TR/json-ld11/#dfn-context-definition), as an [IRI](https://tools.ietf.org/html/rfc3987#section-2), or as an [array](https://infra.spec.whatwg.org/#list) combining either of the above.

In this case, you can see the JSON-LD specification explicitly tells implementors that the value of a context may be a map, IRI, or an array combining maps and IRIs.

**Comment by KisaragiEffective** [comment]
I'm sorry, I must have seen at normal [context](https://www.w3.org/TR/json-ld11/#dfn-context)...
Thank you for quick response :)

**Comment by TallTed** [comment]
@nightpool — Please revisit your https://github.com/w3c/activitystreams/issues/611#issuecomment-2282908070 and code fence the `@context` (simple backticks before and after, like ``` `@context` ``` will do the job) that appears in the quoted segment. Omitting these fences cause alerts and notifications to that user, who has not chosen to participate in nor observe this conversation.

**Comment by nightpool** [comment]
@TallTed I'm sure I'm not the first or the last person to accidentally @-mention that particular user, it's the hazard of having a common-word Github username. The user does not appear to have logged into their Github account in many years, and probably receive dozens of mentions a day from unknowing users, so I think the extra noise created by you leaving this comment on every single issue seriously outweighs any good this reminder does for the user in question. Please stop clogging up issue threads with them.
