### ISSUE TITLE
Mechanism to signal "bot actors" or automated actors

### ISSUE THREAD

**Issue by ThisIsMissEm** [w3c/activitystreams#614]
> Another thing I would probably consider is a property like `automated: true` that can be used to signal "bot accounts" regardless of the actor `type`. I can very easily imagine a case where you would want the `type` to be `Person` since the actor represents an individual person, but you also want to signal that the actor produces automated activities and/or is generally not monitored. Over time, usage of such a property should replace current usage of Application/Service for this purpose, since that has always been a hack and we haven't actually reached 100% consensus for those types -- aside from silverpill's comments above, there is still an open sub-issue for `Service` being "a service of any kind" and this definition covering commercial services, legal services, etc. I think there should be disambiguation for these use cases mentioned in the Primer as well, and potentially some more thought given to what the best way would be to represent those semantics for service types that are not strictly a social networking service.

_Originally posted by @trwnh in https://github.com/w3c/activitystreams/issues/563#issuecomment-2307469481_

**Comment by ThisIsMissEm** [comment]
@evanp you can go ahead and mark this straight away as "Needs FEP"

**Comment by evanp** [comment]
> @evanp you can go ahead and mark this straight away as "Needs FEP"

We already have a mechanism to do this, which is using `Application` or `Service`. If it's really important to show that the actor is also a `Person`, that could be done with multityping.

I think it's fine to write a FEP about, though, since it's not covered in the main specs.
