### ISSUE TITLE
attributedTo range and example 68 appear contradictory

### ISSUE THREAD

**Issue by JacksonBailey** [w3c/activitystreams#617]
Please Indicate One: 
 * [x] Editorial
 * [ ] Question
 * [ ] Feedback
 * [ ] Blocking Issue
 * [ ] Non-Blocking Issue

Please Describe the Issue:

The [`attributedTo`](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-attributedto) property has a range of `Object | Link`, but in example 68 (below) it looks like it can also be an `xsd:anyURI`.

```json
{
  "@context": "https://www.w3.org/ns/activitystreams",
  "type": "Image",
  "name": "My cat taking a nap",
  "url": "http://example.org/cat.jpeg",
  "attributedTo": [
    "http://joe.example.org",
    {
      "type": "Person",
      "name": "Sally"
    }
  ]
}
```

**Comment by JacksonBailey** [comment]
Similar discrepancy with [context](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-context) and example 73.

```json
{
  "@context": "https://www.w3.org/ns/activitystreams",
  "summary": "Activities in context 1",
  "type": "Collection",
  "items": [
    {
      "type": "Offer",
      "actor": "http://sally.example.org",
      "object": "http://example.org/posts/1",
      "target": "http://john.example.org",
      "context": "http://example.org/contexts/1"
    },
    {
      "type": "Like",
      "actor": "http://joe.example.org",
      "object": "http://example.org/posts/2",
      "context": "http://example.org/contexts/1"
    }
  ]
}
```

**Comment by nightpool** [comment]
This is not an error, it's just a nuance of how object links are represented in JSON-LD. When you see a URI value, it's an indication that the resource resolved by fetching the URI is going to be an `Object` or a `Link`.

`Object` doesn't mean that the entire object will be represented inline, just that `http://example.org/contexts/1`, once you resolve it, is going to be a descendent of the super-type `Object`.
